// Code generated by internal/icongen. DO NOT EDIT.
//
// Phosphor Icons 2.1.1, regular weight, from
// https://github.com/phosphor-icons/core
// at commit 2b75f3ad12b420c9504ef05df8d2564a28f8500e.
//
// The paths are MIT, Copyright (c) 2023 Phosphor Icons. The licence is in
// LICENSE.md beside this file.

package icons

import "html/template"

// Jar is the Phosphor "jar" icon. Tags: mason jar, kitchen, pantry,
// canning, preserves, food, condiments.
func Jar(p Props) template.HTML {
	return draw(p, `M184,48.81V32a16,16,0,0,0-16-16H88A16,16,0,0,0,72,32V48.81A40.05,40.05,0,0,0,40,88V200a40,40,0,0,0,40,40h96a40,40,0,0,0,40-40V88A40.05,40.05,0,0,0,184,48.81ZM168,48H152V32h16Zm-48,0V32h16V48ZM104,32V48H88V32Zm96,168a24,24,0,0,1-24,24H80a24,24,0,0,1-24-24V88A24,24,0,0,1,80,64h96a24,24,0,0,1,24,24Z`)
}

// JarLabel is the Phosphor "jar-label" icon. Tags: mason jar, kitchen,
// pantry, canning, preserves, food, condiments.
func JarLabel(p Props) template.HTML {
	return draw(p, `M184,48.81V32a16,16,0,0,0-16-16H88A16,16,0,0,0,72,32V48.81A40.05,40.05,0,0,0,40,88V200a40,40,0,0,0,40,40h96a40,40,0,0,0,40-40V88A40.05,40.05,0,0,0,184,48.81ZM56,112H200v64H56ZM168,48H152V32h16Zm-48,0V32h16V48ZM104,32V48H88V32ZM80,64h96a24,24,0,0,1,24,24v8H56V88A24,24,0,0,1,80,64Zm96,160H80a24,24,0,0,1-24-24v-8H200v8A24,24,0,0,1,176,224Z`)
}

// Jeep is the Phosphor "jeep" icon. Tags: *updated*, vehicles,
// automobile, suv, cars, trucks, wrangler, off-road, transit,
// transportation, traveling.
func Jeep(p Props) template.HTML {
	return draw(p, `M240,88h-9.53l-9.29-43.35A16.08,16.08,0,0,0,205.53,32H50.47A16.08,16.08,0,0,0,34.82,44.65L25.53,88H16a8,8,0,0,0,0,16h8v96a16,16,0,0,0,16,16H64a16,16,0,0,0,16-16V176h96v24a16,16,0,0,0,16,16h24a16,16,0,0,0,16-16V104h8a8,8,0,0,0,0-16ZM50.47,48H205.53l8.57,40H41.9ZM64,200H40V176H64Zm128,0V176h24v24Zm24-40H152V128a8,8,0,0,0-16,0v32H120V128a8,8,0,0,0-16,0v32H40V104H216ZM56,132a12,12,0,1,1,12,12A12,12,0,0,1,56,132Zm120,0a12,12,0,1,1,12,12A12,12,0,0,1,176,132Z`)
}

// Joystick is the Phosphor "joystick" icon. Tags: gaming, game
// controller, video games, arcade game, atari.
func Joystick(p Props) template.HTML {
	return draw(p, `M208,144H136V95.19a40,40,0,1,0-16,0V144H48a16,16,0,0,0-16,16v48a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V160A16,16,0,0,0,208,144ZM104,56a24,24,0,1,1,24,24A24,24,0,0,1,104,56ZM208,208H48V160H208v48Zm-40-96h32a8,8,0,0,1,0,16H168a8,8,0,0,1,0-16Z`)
}
