package feature

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// componentsDir is the package this file reads, from where the test binary runs.
//
// A test in this tree runs with its own directory as the working directory, so
// the package under test is named by a path rather than by ".".
const componentsDir = "../../components"

// TestTheGeneratedFilesMatchTheirSources.
//
// The .go files are committed, because a module whose generated files are
// missing is one `go get` cannot use. That makes a stale one shippable: the
// source says one thing, the published package does another, and nothing in the
// build notices.
//
// This does not recompile -- that would need the view compiler, which is in aru
// and would make this module depend on the CLI. It checks the weaker property
// that catches the real mistake: every source has an output, every output has a
// source, and the output names the source it came from.
//
// A missing output is caught earlier and harder: the package stops compiling,
// because the function it declared is gone. What only this test catches is the
// other direction -- a .go left behind by a component that was renamed, which
// compiles perfectly and ships a component nobody maintains.
func TestTheGeneratedFilesMatchTheirSources(t *testing.T) {
	entries, err := os.ReadDir(componentsDir)
	if err != nil {
		t.Fatal(err)
	}

	sources, generated := map[string]bool{}, map[string]bool{}
	for _, e := range entries {
		switch name := e.Name(); {
		case strings.HasSuffix(name, ".kyse.go"):
			sources[strings.TrimSuffix(name, ".kyse.go")] = true
		case strings.HasSuffix(name, "_test.go"):
		case strings.HasSuffix(name, ".go"):
			// Generated is decided by the header the generator writes, not by
			// "everything that is not doc.go". This package also holds
			// hand-written Go -- page.go is the contract an input asks through
			// -- and a list of exceptions by name is a list somebody forgets to
			// add to, which is how page.go came to be reported as an orphan.
			body, err := os.ReadFile(filepath.Join(componentsDir, name))
			if err != nil {
				t.Fatal(err)
			}
			if strings.HasPrefix(string(body), "// Code generated by") {
				generated[strings.TrimSuffix(name, ".go")] = true
			}
		}
	}

	if len(sources) == 0 {
		t.Fatal("no .kyse.go sources: this test is proving nothing")
	}

	for name := range sources {
		if !generated[name] {
			t.Errorf("%s.kyse.go has no compiled %s.go: run `aru view:build` and commit it", name, name)
			continue
		}
		body, err := os.ReadFile(filepath.Join(componentsDir, name+".go"))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(body), name+".kyse.go") {
			t.Errorf("%s.go does not name the source it came from", name)
		}
	}
	for name := range generated {
		if !sources[name] {
			t.Errorf("%s.go has no source: it is left over from a component that was renamed or removed", name)
		}
	}
}
