// Code generated by `aru view:build` from accordion.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"github.com/arandu-io/kyse/icons"
	"html/template"
)

//line components/accordion.kyse.go:11

// AccordionProps is a stack of headings, each with a section folded behind it.
//
// It is details and summary, which is the disclosure the browser already has.
// The open state, the click, Enter and Space, the announcement to a screen
// reader, and find-in-page expanding a closed section are five behaviours
// nobody writes here -- and they are the five a hand-built accordion drops one
// of. There is no role and no aria-expanded on it for the same reason: the
// elements carry both already, and writing them again is how they come to
// disagree with the state.
//
// One section open at a time is an attribute rather than a script. Two details
// elements that share a name are exclusive to each other, and the browser
// closes the one that was open when the next is unfolded.
type AccordionProps struct {
	// ID is the name the sections share, which is what makes opening one close
	// the last. Two accordions on a page need two, and an empty ID leaves every
	// section independent whatever Multiple says.
	ID string
	// Items are the sections, top to bottom.
	Items []AccordionItem
	// Multiple lets more than one section stand open at once.
	Multiple bool
}

// AccordionItem is one section: the heading that is always visible, and what is
// behind it.
type AccordionItem struct {
	// Label is the heading, and what is clicked.
	Label string
	// Content is what the section holds. It is markup rather than text, so it
	// comes from another component or from a view -- and both of those escaped
	// whatever a person wrote on the way in.
	Content template.HTML
	// Open draws this section already unfolded. When the sections are exclusive
	// the browser keeps the first of several.
	Open bool
	// Disabled makes the section neither clickable nor reachable by keyboard.
	// The stylesheet stops the pointer and the heading leaves the tab order,
	// which together are the two ways a section is opened. It is said on the
	// heading rather than on the section, because the heading is the control.
	Disabled bool
}

// Group is the name the sections share, or empty when each opens on its own.
func (p AccordionProps) Group() string {
	if p.Multiple {
		return ""
	}
	return p.ID
}

//line components/accordion.go:71

// Accordion renders the accordion component.
func Accordion(kyse__props AccordionProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<section\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"accordion\"\n")
	}
//line components/accordion.kyse.go:66
	if kyse__d.ID != "" {
//line components/accordion.go:92
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
		}
		if kyse__err == nil {
//line components/accordion.kyse.go:67
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/accordion.go:99
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
//line components/accordion.kyse.go:70
	for _, item := range kyse__d.Items {
		_ = item
//line components/accordion.go:111
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<details\n")
		}
//line components/accordion.kyse.go:72
		if kyse__d.Group() != "" {
//line components/accordion.go:117
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tname=\"")
			}
			if kyse__err == nil {
//line components/accordion.kyse.go:73
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Group()))
//line components/accordion.go:124
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
//line components/accordion.kyse.go:75
		if item.Open {
//line components/accordion.go:132
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\topen\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<summary\n")
		}
//line components/accordion.kyse.go:80
		if item.Disabled {
//line components/accordion.go:145
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\taria-disabled=\"true\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\ttabindex=\"-1\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
		}
		if kyse__err == nil {
//line components/accordion.kyse.go:84
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(item.Label)))
//line components/accordion.go:159
		}
		if kyse__err == nil {
//line components/accordion.kyse.go:84
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(icons.CaretDown(icons.Props{})))
//line components/accordion.go:164
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</summary>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<section>")
		}
		if kyse__err == nil {
//line components/accordion.kyse.go:85
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(item.Content))
//line components/accordion.go:175
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</section>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</details>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</section>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
