// Code generated by `aru view:build` from autocomplete.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"strconv"
)

//line components/autocomplete.kyse.go:7

// AutocompleteProps is a text box with suggestions the browser draws itself.
//
// It is an input and a datalist, and the list is drawn, positioned, filtered
// and dismissed by the browser. That is the whole difference from a
// [Combobox]: this one suggests, and a combobox chooses. What is typed here is
// the value whether or not it is in the list -- a town nobody has heard of, a
// tag that does not exist yet -- and what a combobox submits has to be one of
// the options it was given.
//
// So the two are not the same control with a flag between them. A combobox
// refuses a value off its list and needs a URL to have a list at all; this
// accepts anything and can have its suggestions in the page.
//
// The suggestions can also come from the server, which is what SearchURL is:
// the datalist is swapped, not the box, so what is typed is never disturbed by
// an answer arriving.
//
// It publishes root, label, input, message and hint.
type AutocompleteProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// Page is where a rejected value and its message come from.
	Page Page
	// Name is the field name, and the id the label points at.
	Name string
	// Label is the text above the box.
	Label string
	// Value is what is in the box when nothing was rejected.
	Value string
	// Options are the suggestions. They are offered, never enforced.
	Options []AutocompleteOption
	// SearchURL replaces the suggestions as somebody types, by swapping the
	// list. Empty leaves the suggestions as they were drawn, which is the
	// right answer for a set that fits on the page.
	SearchURL string
	// Delay is how long typing pauses before the suggestions are fetched, in
	// milliseconds. Zero waits 200, which is long enough that a word typed at
	// speed is one request and short enough that nobody waits for it.
	Delay int
	// Placeholder is the grey text in the empty box.
	Placeholder string
	// Hint is the sentence under it while nothing is wrong.
	Hint string
	// Required marks the field.
	Required bool
	// Disabled draws it unavailable.
	Disabled bool
	// MaxLength is the ceiling the browser enforces while typing. Zero leaves
	// it open.
	MaxLength int
}

// AutocompleteOption is one suggestion.
type AutocompleteOption struct {
	// Value is what is put in the box when the suggestion is taken, and what
	// the form then submits.
	Value string
	// Label is the description shown beside it: the airport for a code, the
	// full name for a handle. Empty shows the value alone.
	Label string
}

// Current is what is in the box: what came back rejected, or what the caller
// set.
func (p AutocompleteProps) Current() string {
	if p.Page == nil {
		return p.Value
	}
	return p.Page.OldOr(p.Name, p.Value)
}

// ListID is the id of the datalist, which the box points at with list.
func (p AutocompleteProps) ListID() string { return p.Name + "-suggestions" }

// Trigger is when the suggestions are fetched: after typing has paused, and
// only when what is in the box actually changed. Without the changed guard,
// an arrow key or a modifier would fetch the same list again.
func (p AutocompleteProps) Trigger() string {
	delay := p.Delay
	if delay <= 0 {
		delay = 200
	}
	return "input changed delay:" + strconv.Itoa(delay) + "ms"
}

// Message is the rejection for this field, and empty when there is none.
func (p AutocompleteProps) Message() string {
	if p.Page == nil {
		return ""
	}
	return p.Page.FieldError(p.Name)
}

// DescribedBy is the id of whatever is explaining the box.
func (p AutocompleteProps) DescribedBy() string {
	if p.Message() != "" {
		return p.Name + "-error"
	}
	if p.Hint != "" {
		return p.Name + "-hint"
	}
	return ""
}

// PartNames are the parts this component publishes.
func (p AutocompleteProps) PartNames() []string {
	return []string{"root", "label", "input", "list", "message", "hint"}
}

//line components/autocomplete.go:129

// Autocomplete renders the autocomplete component.
func Autocomplete(kyse__props AutocompleteProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:120
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("field")))
//line components/autocomplete.go:154
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/autocomplete.kyse.go:121
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/autocomplete.go:163
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:121", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<label\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"label\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:125
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("label", "label")))
//line components/autocomplete.go:185
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tfor=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:126
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/autocomplete.go:196
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v2 string
//line components/autocomplete.kyse.go:127
		kyse__v2, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("label"))
//line components/autocomplete.go:205
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:127", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:128
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Label)))
//line components/autocomplete.go:218
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</label>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<input\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"input\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:136
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("input", "input")))
//line components/autocomplete.go:238
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\ttype=\"text\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:138
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/autocomplete.go:252
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tname=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:139
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/autocomplete.go:263
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tvalue=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:140
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Current()))
//line components/autocomplete.go:274
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tlist=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:141
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListID()))
//line components/autocomplete.go:285
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tautocomplete=\"off\"\n")
	}
	if kyse__err == nil {
		var kyse__v3 string
//line components/autocomplete.kyse.go:143
		kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("input"))
//line components/autocomplete.go:297
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:143", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
		}
	}
//line components/autocomplete.kyse.go:144
	if kyse__d.SearchURL != "" {
//line components/autocomplete.go:306
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\thx-get=\"")
		}
		if kyse__err == nil {
			var kyse__v4 string
//line components/autocomplete.kyse.go:145
			kyse__v4, kyse__err = kyse__view.TextURL(kyse__d.SearchURL)
//line components/autocomplete.go:314
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:145", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\thx-trigger=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:146
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Trigger()))
//line components/autocomplete.go:330
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\thx-target=\"#")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:147
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListID()))
//line components/autocomplete.go:341
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\thx-swap=\"innerHTML\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\thx-sync=\"this:replace\"\n")
		}
	}
//line components/autocomplete.kyse.go:151
	if kyse__d.Placeholder != "" {
//line components/autocomplete.go:355
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tplaceholder=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:152
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Placeholder))
//line components/autocomplete.go:362
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/autocomplete.kyse.go:154
	if kyse__d.MaxLength > 0 {
//line components/autocomplete.go:370
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tmaxlength=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:155
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.MaxLength))
//line components/autocomplete.go:377
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/autocomplete.kyse.go:157
	if kyse__d.DescribedBy() != "" {
//line components/autocomplete.go:385
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-describedby=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:158
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.DescribedBy()))
//line components/autocomplete.go:392
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/autocomplete.kyse.go:160
	if kyse__d.Message() != "" {
//line components/autocomplete.go:400
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-invalid=\"true\"\n")
		}
	}
//line components/autocomplete.kyse.go:163
	if kyse__d.Required {
//line components/autocomplete.go:407
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\trequired\n")
		}
	}
//line components/autocomplete.kyse.go:166
	if kyse__d.Disabled {
//line components/autocomplete.go:414
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdisabled\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<datalist\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"list\"\n")
	}
//line components/autocomplete.kyse.go:173
	if kyse__d.PartClass("list") != "" {
//line components/autocomplete.go:433
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:174
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("list")))
//line components/autocomplete.go:440
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
	}
	if kyse__err == nil {
//line components/autocomplete.kyse.go:176
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListID()))
//line components/autocomplete.go:452
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v5 string
//line components/autocomplete.kyse.go:177
		kyse__v5, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("list"))
//line components/autocomplete.go:461
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:177", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v5)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
//line components/autocomplete.kyse.go:179
	for _, option := range kyse__d.Options {
		_ = option
//line components/autocomplete.go:474
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<option\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tvalue=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:181
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(option.Value))
//line components/autocomplete.go:484
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
//line components/autocomplete.kyse.go:182
		if option.Label != "" {
//line components/autocomplete.go:491
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tlabel=\"")
			}
			if kyse__err == nil {
//line components/autocomplete.kyse.go:183
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(option.Label))
//line components/autocomplete.go:498
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t></option>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</datalist>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
//line components/autocomplete.kyse.go:189
	if kyse__d.Message() != "" {
//line components/autocomplete.go:516
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<p\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"message\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:192
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/autocomplete.go:529
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "-error\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:193
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("message", "text-destructive text-sm")))
//line components/autocomplete.go:540
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v6 string
//line components/autocomplete.kyse.go:194
			kyse__v6, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("message"))
//line components/autocomplete.go:549
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:194", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>")
		}
		if kyse__err == nil {
//line components/autocomplete.kyse.go:195
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Message())))
//line components/autocomplete.go:562
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
//line components/autocomplete.kyse.go:197
	if kyse__d.Message() == "" {
//line components/autocomplete.go:570
//line components/autocomplete.kyse.go:198
		if kyse__d.Hint != "" {
//line components/autocomplete.go:573
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<p\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"hint\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/autocomplete.kyse.go:201
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/autocomplete.go:586
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "-hint\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/autocomplete.kyse.go:202
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("hint", "text-muted-foreground text-sm")))
//line components/autocomplete.go:597
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				var kyse__v7 string
//line components/autocomplete.kyse.go:203
				kyse__v7, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("hint"))
//line components/autocomplete.go:606
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/autocomplete.kyse.go:203", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v7)
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
			}
			if kyse__err == nil {
//line components/autocomplete.kyse.go:204
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Hint)))
//line components/autocomplete.go:619
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
			}
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
