// Code generated by `aru view:build` from avatar.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"strings"
)

//line components/avatar.kyse.go:7

// AvatarProps is who somebody is, in a circle.
//
// With no image it draws initials, which is the case that actually happens: an
// application where everybody uploaded a photograph does not exist, and a broken
// image icon beside every comment is worse than two letters.
// It publishes one part, root, which is the circle itself.
type AvatarProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// Name is the person. It is the alt text, and the initials come from it.
	Name string
	// ImageURL is their picture. Empty draws the initials.
	ImageURL string
	// Size is "sm", "lg", or empty for the default.
	Size string
}

// Initials are the first letters of the first and last word of the name.
//
// First and LAST, not the first two: "Ada B. Lovelace" is AL, and the version
// that walked forwards until it had two letters answered AB -- a middle initial
// where a surname belongs. Nobody would have noticed from looking at the
// component; the letters are the right shape either way.
//
// It walks runes rather than bytes: a name starting with É is one letter to a
// person and two bytes to Go, and slicing bytes would print half a character.
func (p AvatarProps) Initials() string {
	words := strings.Fields(p.Name)
	if len(words) == 0 {
		return ""
	}

	out := []rune{[]rune(words[0])[0]}
	if len(words) > 1 {
		out = append(out, []rune(words[len(words)-1])[0])
	}
	return strings.ToUpper(string(out))
}

// PartNames are the parts this component publishes.
func (p AvatarProps) PartNames() []string { return []string{"root"} }

//line components/avatar.go:62

// Avatar renders the avatar component.
func Avatar(kyse__props AvatarProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<span\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/avatar.kyse.go:53
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("avatar")))
//line components/avatar.go:87
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/avatar.kyse.go:54
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/avatar.go:96
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/avatar.kyse.go:54", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
//line components/avatar.kyse.go:55
	if kyse__d.Size != "" {
//line components/avatar.go:105
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-size=\"")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:56
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Size))
//line components/avatar.go:112
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
//line components/avatar.kyse.go:59
	if kyse__d.ImageURL != "" {
//line components/avatar.go:123
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<img src=\"")
		}
		if kyse__err == nil {
			var kyse__v2 string
//line components/avatar.kyse.go:60
			kyse__v2, kyse__err = kyse__view.TextURL(kyse__d.ImageURL)
//line components/avatar.go:131
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/avatar.kyse.go:60", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" alt=\"")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:60
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/avatar.go:144
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
		}
	}
//line components/avatar.kyse.go:62
	if kyse__d.ImageURL == "" {
//line components/avatar.go:152
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span aria-hidden=\"true\">")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:63
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Initials())))
//line components/avatar.go:159
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span class=\"sr-only\">")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:64
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Name)))
//line components/avatar.go:170
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
