// Code generated by `aru view:build` from avatar.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"strings"
)

//line components/avatar.kyse.go:7

// AvatarProps is who somebody is, in a circle.
//
// With no image it draws initials, which is the case that actually happens: an
// application where everybody uploaded a photograph does not exist, and a broken
// image icon beside every comment is worse than two letters.
//
// # What it publishes
//
// Three parts: root, the circle itself; image, the picture; and initials, the
// two letters that stand in for one. The two inner ones never appear together --
// which one is drawn is what ImageURL decides -- and they are published because
// they are what a caller reaches for: how the picture is cropped and how heavy
// the letters read are both decisions about this avatar rather than about every
// avatar.
//
// The name beside the initials is not a part. It is the sentence a screen reader
// is given in place of the letters, and its class is what keeps it out of the
// circle; a handle for it would be a handle for breaking that.
type AvatarProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// Name is the person. It is the alt text, and the initials come from it.
	Name string
	// ImageURL is their picture. Empty draws the initials.
	ImageURL string
	// Size is "sm", "lg", or empty for the default.
	Size string
}

// Initials are the first letters of the first and last word of the name.
//
// First and LAST, not the first two: "Ada B. Lovelace" is AL, and the version
// that walked forwards until it had two letters answered AB -- a middle initial
// where a surname belongs. Nobody would have noticed from looking at the
// component; the letters are the right shape either way.
//
// It walks runes rather than bytes: a name starting with É is one letter to a
// person and two bytes to Go, and slicing bytes would print half a character.
func (p AvatarProps) Initials() string {
	words := strings.Fields(p.Name)
	if len(words) == 0 {
		return ""
	}

	out := []rune{[]rune(words[0])[0]}
	if len(words) > 1 {
		out = append(out, []rune(words[len(words)-1])[0])
	}
	return strings.ToUpper(string(out))
}

// PartNames are the parts this component publishes.
func (p AvatarProps) PartNames() []string { return []string{"root", "image", "initials"} }

//line components/avatar.go:74

// Avatar renders the avatar component.
func Avatar(kyse__props AvatarProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<span\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/avatar.kyse.go:65
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("avatar")))
//line components/avatar.go:99
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/avatar.kyse.go:66
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/avatar.go:108
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/avatar.kyse.go:66", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
//line components/avatar.kyse.go:67
	if kyse__d.Size != "" {
//line components/avatar.go:117
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-size=\"")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:68
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Size))
//line components/avatar.go:124
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
//line components/avatar.kyse.go:71
	if kyse__d.ImageURL != "" {
//line components/avatar.go:135
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<img\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"image\"\n")
		}
//line components/avatar.kyse.go:74
		if kyse__d.PartClass("image") != "" {
//line components/avatar.go:144
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/avatar.kyse.go:75
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("image")))
//line components/avatar.go:151
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tsrc=\"")
		}
		if kyse__err == nil {
			var kyse__v2 string
//line components/avatar.kyse.go:77
			kyse__v2, kyse__err = kyse__view.TextURL(kyse__d.ImageURL)
//line components/avatar.go:164
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/avatar.kyse.go:77", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\talt=\"")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:78
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/avatar.go:180
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v3 string
//line components/avatar.kyse.go:79
			kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("image"))
//line components/avatar.go:189
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/avatar.kyse.go:79", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
		}
	}
//line components/avatar.kyse.go:82
	if kyse__d.ImageURL == "" {
//line components/avatar.go:202
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"initials\"\n")
		}
//line components/avatar.kyse.go:85
		if kyse__d.PartClass("initials") != "" {
//line components/avatar.go:211
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/avatar.kyse.go:86
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("initials")))
//line components/avatar.go:218
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-hidden=\"true\"\n")
		}
		if kyse__err == nil {
			var kyse__v4 string
//line components/avatar.kyse.go:89
			kyse__v4, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("initials"))
//line components/avatar.go:231
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/avatar.kyse.go:89", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:90
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Initials())))
//line components/avatar.go:244
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span class=\"sr-only\">")
		}
		if kyse__err == nil {
//line components/avatar.kyse.go:91
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Name)))
//line components/avatar.go:255
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
