// Code generated by `aru view:build` from badge.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/framework/view"
)

//line components/badge.kyse.go:5

// BadgeProps is a small piece of status beside something else: published or
// draft, open or closed, the count on a tab.
type BadgeProps struct {
	// Label is the text.
	Label string
	// Variant is "primary", "secondary", "outline", "ghost", "destructive" or
	// "link". Empty is the default.
	Variant string
}

//line components/badge.go:28

// Badge renders the badge component.
func Badge(kyse__props BadgeProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<span\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"badge\"\n")
	}
//line components/badge.kyse.go:19
	if kyse__d.Variant != "" {
//line components/badge.go:49
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-variant=\"")
		}
		if kyse__err == nil {
//line components/badge.kyse.go:20
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Variant))
//line components/badge.go:56
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">")
	}
	if kyse__err == nil {
//line components/badge.kyse.go:22
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Label)))
//line components/badge.go:68
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__view.UnsafeText
	_ = kyse__strings.Builder{}
)
