// Code generated by `aru view:build` from breadcrumb.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"fmt"
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/icons"
)

//line components/breadcrumb.kyse.go:7

// BreadcrumbProps is the trail from the front of a site down to where somebody
// is standing.
//
// The last crumb is the page being looked at, so it is drawn as text and not as
// a link, and it carries aria-current -- which is the part that is announced.
// A trail whose last entry links to the page it is already on is the mistake
// this shape cannot make: the current page is taken from the end of the list
// and its address is never read.
//
// The separators are drawn here rather than by the caller, and they are marked
// hidden. A screen reader that reads the arrows aloud reads the trail as
// "Home, greater than, Posts, greater than", which is four words of punctuation
// for three of content.
type BreadcrumbProps struct {
	// Items are the crumbs, from the outermost down to the page itself. Empty
	// draws an empty trail rather than a stray separator.
	Items []Crumb
	// Label names the landmark for a screen reader, so a page with two
	// navigations is not two of the same word. Empty means "Breadcrumb".
	Label string
}

// Crumb is one step of the trail.
type Crumb struct {
	// Label is the text.
	Label string
	// URL is where the step goes. Empty draws it as plain text, which is what a
	// grouping with no page behind it is. It is ignored on the last crumb.
	URL string
}

// Trail is every crumb above the current page.
func (p BreadcrumbProps) Trail() []Crumb {
	if len(p.Items) == 0 {
		return nil
	}
	return p.Items[:len(p.Items)-1]
}

// Current is the page being looked at, which is the last crumb.
func (p BreadcrumbProps) Current() Crumb {
	if len(p.Items) == 0 {
		return Crumb{}
	}
	return p.Items[len(p.Items)-1]
}

// Landmark is what the navigation is announced as.
func (p BreadcrumbProps) Landmark() string {
	if p.Label == "" {
		return "Breadcrumb"
	}
	return p.Label
}

//line components/breadcrumb.go:75

// Breadcrumb renders the breadcrumb component.
func Breadcrumb(props BreadcrumbProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<nav class=\"breadcrumb\" aria-label=\"")
	}
	if err == nil {
//line components/breadcrumb.kyse.go:64
		_, err = io.WriteString(w, view.TextAttr(d.Landmark()))
//line components/breadcrumb.go:92
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<ol>\n")
	}
//line components/breadcrumb.kyse.go:66
	for _, crumb := range d.Trail() {
		_ = crumb
//line components/breadcrumb.go:103
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<li>\n")
		}
//line components/breadcrumb.kyse.go:68
		if crumb.URL != "" {
//line components/breadcrumb.go:109
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<a href=\"")
			}
			if err == nil {
				var s string
//line components/breadcrumb.kyse.go:69
				s, err = view.TextURL(crumb.URL)
//line components/breadcrumb.go:117
				if err != nil {
					err = fmt.Errorf("%s: %w", "components/breadcrumb.kyse.go:69", err)
				} else {
					_, err = io.WriteString(w, s)
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\">")
			}
			if err == nil {
//line components/breadcrumb.kyse.go:69
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(crumb.Label)))
//line components/breadcrumb.go:130
			}
			if err == nil {
				_, err = io.WriteString(w, "</a>\n")
			}
		} else {
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<span>")
			}
			if err == nil {
//line components/breadcrumb.kyse.go:71
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(crumb.Label)))
//line components/breadcrumb.go:142
			}
			if err == nil {
				_, err = io.WriteString(w, "</span>\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t</li>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<li aria-hidden=\"true\" data-rtl-flip>")
		}
		if err == nil {
//line components/breadcrumb.kyse.go:74
			_, err = io.WriteString(w, view.UnsafeText(icons.CaretRight(icons.Props{})))
//line components/breadcrumb.go:157
		}
		if err == nil {
			_, err = io.WriteString(w, "</li>\n")
		}
	}
//line components/breadcrumb.kyse.go:76
	if len(d.Items) > 0 {
//line components/breadcrumb.go:165
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<li><span aria-current=\"page\">")
		}
		if err == nil {
//line components/breadcrumb.kyse.go:77
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Current().Label)))
//line components/breadcrumb.go:172
		}
		if err == nil {
			_, err = io.WriteString(w, "</span></li>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</ol>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</nav>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
