// Code generated by `aru view:build` from card.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line components/card.kyse.go:5

// CardProps is one item in a list: a title, a sentence, and where it goes.
//
// It does not take content. A component that wrapped arbitrary markup would
// have to receive it as a string of HTML, and a string of HTML is the one thing
// this view layer refuses to accept -- it is exactly where escaping stops being
// guaranteed by construction. So a card takes the fields it draws, and markup
// that needs a frame around it uses `class="card"` directly.
type CardProps struct {
	// Title is the heading, and the link text when Href is set.
	Title string
	// Description is the sentence under it.
	Description string
	// Href makes the title a link. Empty draws a plain card.
	Href string
	// Meta is the small grey line at the bottom: a date, an author, a count.
	Meta string
	// Badge draws a badge beside the title. Empty draws none.
	Badge string
	// BadgeVariant styles it. See BadgeProps.
	BadgeVariant string
}

//line components/card.go:41

// Card renders the card component.
func Card(kyse__props CardProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<article class=\"card p-5\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<header class=\"flex items-start justify-between gap-3\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<h3 class=\"font-semibold tracking-tight\">\n")
	}
//line components/card.kyse.go:32
	if kyse__d.Href != "" {
//line components/card.go:65
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<a class=\"hover:underline\" href=\"")
		}
		if kyse__err == nil {
			var kyse__v1 string
//line components/card.kyse.go:33
			kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.Href)
//line components/card.go:73
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/card.kyse.go:33", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\">")
		}
		if kyse__err == nil {
//line components/card.kyse.go:33
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line components/card.go:86
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</a>\n")
		}
	}
//line components/card.kyse.go:35
	if kyse__d.Href == "" {
//line components/card.go:94
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t")
		}
		if kyse__err == nil {
//line components/card.kyse.go:36
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line components/card.go:101
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</h3>\n")
	}
//line components/card.kyse.go:39
	if kyse__d.Badge != "" {
//line components/card.go:112
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t")
		}
		if kyse__err == nil {
//line components/card.kyse.go:40
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(Badge(BadgeProps{Label: kyse__d.Badge, Variant: kyse__d.BadgeVariant})))
//line components/card.go:119
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
//line components/card.kyse.go:44
	if kyse__d.Description != "" {
//line components/card.go:133
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<p class=\"text-muted-foreground mt-2 text-sm\">")
		}
		if kyse__err == nil {
//line components/card.kyse.go:45
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Description)))
//line components/card.go:140
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
//line components/card.kyse.go:47
	if kyse__d.Meta != "" {
//line components/card.go:148
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<p class=\"text-muted-foreground mt-3 text-xs\">")
		}
		if kyse__err == nil {
//line components/card.kyse.go:48
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Meta)))
//line components/card.go:155
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</article>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
