// Code generated by `aru view:build` from checkbox.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/checkbox.kyse.go:5

// CheckboxProps is one box that is either ticked or not, with its label beside
// it rather than above it.
//
// Field cannot draw this and should not be asked to. Its row is a name over a
// box somebody types into, and it carries a string; a checkbox is a box with the
// name to its right, and what it carries is a yes or a no. Branching Field on
// which of the two it was would be two components sharing one name.
//
// Use it for consent and for one answer of many on a form somebody submits. Use
// Switch for a setting that takes effect when it is thrown.
type CheckboxProps struct {
	// Name is the form field name, and what Page is asked about.
	Name string
	// ID is the id the markup carries, and the id the label points at. Empty
	// uses Name -- which a list of boxes sharing one name has to set, since
	// otherwise every label in the list points at the first box.
	ID string
	// Label is the text beside the box.
	Label string
	// Value is what a ticked box submits. Empty submits "on", which is what a
	// browser sends for a box with no value of its own.
	Value string
	// Hint is the sentence under the label that is always there.
	Hint string
	// Page is the screen's own view.Page, which is what this box asks for its
	// message and for whether it came back ticked. Nil draws no message and
	// keeps Checked.
	Page Page
	// Checked is whether the box starts ticked when nothing was rejected: the
	// stored record on an edit form, and usually false on a create form.
	Checked bool
	// Required refuses the form until the box is ticked, which is what a consent
	// box wants and what a preference must not have.
	Required bool
	// Disabled takes the box out of the form and out of the tab order.
	Disabled bool
}

// ElementID is the id the box carries: ID when one was given, and Name when
// none was.
func (p CheckboxProps) ElementID() string {
	if p.ID != "" {
		return p.ID
	}
	return p.Name
}

// SubmittedValue is what a ticked box sends: Value when it was given, and "on"
// when it was not.
func (p CheckboxProps) SubmittedValue() string {
	if p.Value == "" {
		return "on"
	}
	return p.Value
}

// Message is what validation left for this box, or empty.
func (p CheckboxProps) Message() string {
	if p.Page == nil {
		return ""
	}
	return p.Page.FieldError(p.Name)
}

// Current reports whether the box is drawn ticked.
//
// A ticked box submits its value and an unticked box submits nothing at all,
// so what comes back from a rejected attempt answers only half the question: the
// value being there means the box was ticked, and it being absent means either
// that it was unticked or that there was no attempt. Absent therefore falls
// back to Checked, which is right on the form nobody submitted and wrong in one
// case -- a box somebody unticked on an attempt that was then rejected comes
// back ticked. Telling the two apart needs a second field on the wire, and this
// component does not invent one.
func (p CheckboxProps) Current() bool {
	if p.Page == nil {
		return p.Checked
	}
	fallback := ""
	if p.Checked {
		fallback = p.SubmittedValue()
	}
	return p.Page.OldOr(p.Name, fallback) == p.SubmittedValue()
}

// DescribedBy names the element that explains this box, so the message and the
// hint are announced rather than only shown.
func (p CheckboxProps) DescribedBy() string {
	if p.Message() != "" {
		return p.ElementID() + "-error"
	}
	if p.Hint != "" {
		return p.ElementID() + "-hint"
	}
	return ""
}

//line components/checkbox.go:115

// Checkbox renders the checkbox component.
func Checkbox(props CheckboxProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\tclass=\"field\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\tdata-orientation=\"horizontal\"\n")
	}
//line components/checkbox.kyse.go:107
	if d.Message() != "" {
//line components/checkbox.go:137
		if err == nil {
			_, err = io.WriteString(w, "\t\tdata-invalid=\"true\"\n")
		}
	}
//line components/checkbox.kyse.go:110
	if d.Disabled {
//line components/checkbox.go:144
		if err == nil {
			_, err = io.WriteString(w, "\t\tdata-disabled=\"true\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, ">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<input\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tclass=\"input\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\ttype=\"checkbox\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tid=\"")
	}
	if err == nil {
//line components/checkbox.kyse.go:117
		_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/checkbox.go:167
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tname=\"")
	}
	if err == nil {
//line components/checkbox.kyse.go:118
		_, err = io.WriteString(w, view.TextAttr(d.Name))
//line components/checkbox.go:178
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
//line components/checkbox.kyse.go:119
	if d.Value != "" {
//line components/checkbox.go:185
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tvalue=\"")
		}
		if err == nil {
//line components/checkbox.kyse.go:120
			_, err = io.WriteString(w, view.TextAttr(d.Value))
//line components/checkbox.go:192
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/checkbox.kyse.go:122
	if d.Current() {
//line components/checkbox.go:200
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tchecked\n")
		}
	}
//line components/checkbox.kyse.go:125
	if d.DescribedBy() != "" {
//line components/checkbox.go:207
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-describedby=\"")
		}
		if err == nil {
//line components/checkbox.kyse.go:126
			_, err = io.WriteString(w, view.TextAttr(d.DescribedBy()))
//line components/checkbox.go:214
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/checkbox.kyse.go:128
	if d.Message() != "" {
//line components/checkbox.go:222
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-invalid=\"true\"\n")
		}
	}
//line components/checkbox.kyse.go:131
	if d.Required {
//line components/checkbox.go:229
		if err == nil {
			_, err = io.WriteString(w, "\t\t\trequired\n")
		}
	}
//line components/checkbox.kyse.go:134
	if d.Disabled {
//line components/checkbox.go:236
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdisabled\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<section>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<label class=\"label\" for=\"")
	}
	if err == nil {
//line components/checkbox.kyse.go:139
		_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/checkbox.go:253
	}
	if err == nil {
		_, err = io.WriteString(w, "\">")
	}
	if err == nil {
//line components/checkbox.kyse.go:139
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Label)))
//line components/checkbox.go:261
	}
	if err == nil {
		_, err = io.WriteString(w, "</label>\n")
	}
//line components/checkbox.kyse.go:140
	if d.Message() != "" {
//line components/checkbox.go:268
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<p id=\"")
		}
		if err == nil {
//line components/checkbox.kyse.go:141
			_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/checkbox.go:275
		}
		if err == nil {
			_, err = io.WriteString(w, "-error\" class=\"text-destructive text-sm\">")
		}
		if err == nil {
//line components/checkbox.kyse.go:141
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Message())))
//line components/checkbox.go:283
		}
		if err == nil {
			_, err = io.WriteString(w, "</p>\n")
		}
	}
//line components/checkbox.kyse.go:143
	if d.Message() == "" {
//line components/checkbox.go:291
//line components/checkbox.kyse.go:144
		if d.Hint != "" {
//line components/checkbox.go:294
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<p id=\"")
			}
			if err == nil {
//line components/checkbox.kyse.go:145
				_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/checkbox.go:301
			}
			if err == nil {
				_, err = io.WriteString(w, "-hint\" class=\"text-muted-foreground text-sm\">")
			}
			if err == nil {
//line components/checkbox.kyse.go:145
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Hint)))
//line components/checkbox.go:309
			}
			if err == nil {
				_, err = io.WriteString(w, "</p>\n")
			}
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</section>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
