// Code generated by `aru view:build` from collapsible.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/icons"
)

//line components/collapsible.kyse.go:7

// CollapsibleProps is one heading and the paragraph it hides: a question with
// its answer, a section of a form nobody opens twice, the detail under a
// summary.
//
// It is <details> and <summary>, so the toggling, the keyboard, the focus and
// the aria-expanded a screen reader reads are the browser's. No script is
// loaded and none is needed, which is also why it keeps working on a page whose
// JavaScript failed.
//
// # This one or a group of them
//
// Use this for a disclosure that stands on its own -- one thing to open, and
// opening it says nothing about anything else on the screen.
//
// Use a group when the items belong to one list and are read as a set: a page
// of frequently asked questions, the sections of a long form. A group is
// written as `class="accordion"` around several <details>, the same way markup
// that needs a frame around it uses `class="card"`. That is not a second
// component to reach for -- it is the same markup, and the stylesheet draws the
// rules between the items only when they are siblings of each other. Several of
// these side by side would be several one-item lists, each with no rule between
// it and the next.
type CollapsibleProps struct {
	// Label is the heading: what opening it will show.
	Label string
	// Content is the text under it.
	Content string
	// Open draws it already open. Use it for the one item somebody came for;
	// a screen where everything starts open is a screen with no summary.
	Open bool
}

//line components/collapsible.go:51

// Collapsible renders the collapsible component.
func Collapsible(props CollapsibleProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<section class=\"accordion\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<details\n")
	}
//line components/collapsible.kyse.go:43
	if d.Open {
//line components/collapsible.go:70
		if err == nil {
			_, err = io.WriteString(w, "\t\t\topen\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<summary>")
	}
	if err == nil {
//line components/collapsible.kyse.go:47
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Label)))
//line components/collapsible.go:84
	}
	if err == nil {
//line components/collapsible.kyse.go:47
		_, err = io.WriteString(w, view.UnsafeText(icons.CaretDown(icons.Props{})))
//line components/collapsible.go:89
	}
	if err == nil {
		_, err = io.WriteString(w, "</summary>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<section>")
	}
	if err == nil {
//line components/collapsible.kyse.go:48
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Content)))
//line components/collapsible.go:100
	}
	if err == nil {
		_, err = io.WriteString(w, "</section>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</details>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</section>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
