// Code generated by `aru view:build` from combobox.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"github.com/arandu-io/kyse/icons"
	"strconv"
)

//line components/combobox.kyse.go:11

// ComboboxProps is a text box that chooses one value out of a list too long to
// put on the page.
//
// # Where the filtering happens
//
// On the server, on every keystroke, and nowhere else: a list short enough to
// send to the browser whole is a list a select already draws, so the component
// that exists for the other case has to keep working at the size that made it
// necessary.
//
// SearchURL is what carries that, and it is not optional. A combobox with no
// URL has no list it could ever show, so it draws nothing rather than a box
// that stays empty however long somebody types into it.
//
// The endpoint answers with this same component, rendered with Options set to
// what it matched. The request asks for the listbox alone and swaps it in
// place, so the endpoint writes no markup of its own and the ARIA below is
// written once.
//
// # What is submitted
//
// Two names. Name carries the chosen value, in a hidden input, and it is what
// the form is about. Query carries the text somebody typed, because the
// browser sends the box it fired the request from and a box with no name sends
// nothing. A handler that only wants the first ignores the second.
type ComboboxProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// Name is the form field name, the id everything else is hung off, and
	// what Page is asked about.
	Name string
	// Label is the text above the box.
	Label string
	// SearchURL is where the list comes from. Empty draws nothing at all.
	SearchURL string
	// QueryParam is the parameter the typed text is sent under. Empty means
	// Name with "-query" after it, which is a name two comboboxes on one page
	// cannot share.
	QueryParam string
	// Options are what the server matched for the current query, in the order
	// it wants them read. Empty on the first paint, which is correct: nobody
	// has typed anything yet.
	Options []ComboboxOption
	// Value is the chosen value when nothing was rejected: the stored record
	// on an edit form, and empty on a create form.
	Value string
	// ValueLabel is what Value reads as in the box. Empty falls back to Value
	// itself, which is right when the value is already a word and wrong when
	// it is an identifier.
	ValueLabel string
	// Placeholder is the grey text inside an empty box.
	Placeholder string
	// Hint is the sentence under the box that is always there.
	Hint string
	// EmptyText is the sentence drawn in place of the list when the server
	// matched nothing. Empty takes the stylesheet's own wording.
	EmptyText string
	// Page is the screen's own view.Page, which is what this box asks for its
	// message and for what was chosen. Nil draws no message and keeps Value.
	Page Page
	// Delay is how long typing pauses before the server is asked, in
	// milliseconds. Zero means 200, which is long enough that a typed word
	// costs one request and short enough that the list feels attached to the
	// keyboard.
	Delay int
	// Required marks the box required, in the markup and to the browser.
	Required bool
	// Disabled draws the box as unavailable and stops it answering.
	Disabled bool
	// Autofocus puts the cursor here on load. At most one per screen.
	Autofocus bool
}

// ComboboxOption is one line of the list.
type ComboboxOption struct {
	// Value is what is submitted when this line is chosen.
	Value string
	// Label is what the line reads as. Empty falls back to Value.
	Label string
	// Disabled draws the line as a suggestion that cannot be chosen. It stays
	// visible, because a line that vanished would read as a list that is
	// missing it.
	Disabled bool
}

// Text is what the option reads as, falling back to the value it carries.
func (o ComboboxOption) Text() string {
	if o.Label == "" {
		return o.Value
	}
	return o.Label
}

// OptionID names one line of the list.
//
// It is numbered rather than named after the value it carries, because
// aria-activedescendant holds an id and an id with a space in it is read as
// two. A value is somebody's data and can hold anything; a position cannot.
//
// The id is what the Enter key is resolved through, so it has to be unique in
// the document: two boxes sharing a Name would number their lines the same and
// the earlier one would answer for both. Name is already required to be unique
// per page for what is submitted, and this is the second reason.
func (p ComboboxProps) OptionID(at int) string {
	return p.Name + "-option-" + strconv.Itoa(at)
}

// ListboxID names the list, which is what the box says it controls and where
// the server's answer is swapped in.
func (p ComboboxProps) ListboxID() string {
	return p.Name + "-listbox"
}

// ListboxTarget is the same list as a selector, for the request.
func (p ComboboxProps) ListboxTarget() string {
	return "#" + p.ListboxID()
}

// Query is the parameter the typed text is sent under.
func (p ComboboxProps) Query() string {
	if p.QueryParam != "" {
		return p.QueryParam
	}
	return p.Name + "-query"
}

// Trigger is when the server is asked: after typing stops, and only when what
// was typed changed.
func (p ComboboxProps) Trigger() string {
	delay := p.Delay
	if delay == 0 {
		delay = 200
	}
	return "input changed delay:" + strconv.Itoa(delay) + "ms"
}

// Message is what validation left for this box, or empty.
func (p ComboboxProps) Message() string {
	if p.Page == nil {
		return ""
	}
	return p.Page.FieldError(p.Name)
}

// Current is the value the box is drawn with: what was chosen on the rejected
// attempt, and Value when there was none.
func (p ComboboxProps) Current() string {
	if p.Page == nil {
		return p.Value
	}
	return p.Page.OldOr(p.Name, p.Value)
}

// CurrentLabel is what Current reads as in the box.
//
// A value that came back from a rejected attempt is a bare value with no label
// beside it, so it is shown as itself. ValueLabel is only right for the value
// it was given for, and using it for another one would put the wrong word in
// the box under a message complaining about the value.
func (p ComboboxProps) CurrentLabel() string {
	if p.Current() != p.Value {
		return p.Current()
	}
	if p.ValueLabel != "" {
		return p.ValueLabel
	}
	return p.Value
}

// DescribedBy names the element that explains this box, so the error and the
// hint are announced rather than only shown.
func (p ComboboxProps) DescribedBy() string {
	if p.Message() != "" {
		return p.Name + "-error"
	}
	if p.Hint != "" {
		return p.Name + "-hint"
	}
	return ""
}

// PartNames are the parts this component publishes.
func (p ComboboxProps) PartNames() []string {
	return []string{"root", "label", "group", "input", "panel", "listbox", "option", "message", "hint"}
}

//line components/combobox.go:207

// Combobox renders the combobox component.
func Combobox(kyse__props ComboboxProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
//line components/combobox.kyse.go:198
	if kyse__d.SearchURL != "" {
//line components/combobox.go:222
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"root\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:201
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("field")))
//line components/combobox.go:235
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v1 string
//line components/combobox.kyse.go:202
			kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/combobox.go:244
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:202", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<label\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"label\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:206
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("label", "label")))
//line components/combobox.go:266
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tfor=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:207
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/combobox.go:277
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v2 string
//line components/combobox.kyse.go:208
			kyse__v2, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("label"))
//line components/combobox.go:286
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:208", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:209
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Label)))
//line components/combobox.go:299
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</label>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<div\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"group\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:219
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("group", "combobox")))
//line components/combobox.go:319
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-combobox\n")
		}
		if kyse__err == nil {
			var kyse__v3 string
//line components/combobox.kyse.go:221
			kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("group"))
//line components/combobox.go:331
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:221", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<input\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"input\"\n")
		}
//line components/combobox.kyse.go:225
		if kyse__d.PartClass("input") != "" {
//line components/combobox.go:349
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:226
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("input")))
//line components/combobox.go:356
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\ttype=\"text\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\trole=\"combobox\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:230
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/combobox.go:374
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v4 string
//line components/combobox.kyse.go:231
			kyse__v4, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("input"))
//line components/combobox.go:383
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:231", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tname=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:232
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Query()))
//line components/combobox.go:396
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tvalue=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:233
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.CurrentLabel()))
//line components/combobox.go:407
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tautocomplete=\"off\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tautocorrect=\"off\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tspellcheck=\"false\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\taria-autocomplete=\"list\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\taria-expanded=\"false\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\taria-controls=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:239
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListboxID()))
//line components/combobox.go:433
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thx-get=\"")
		}
		if kyse__err == nil {
			var kyse__v5 string
//line components/combobox.kyse.go:240
			kyse__v5, kyse__err = kyse__view.TextURL(kyse__d.SearchURL)
//line components/combobox.go:445
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:240", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v5)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thx-trigger=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:241
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Trigger()))
//line components/combobox.go:461
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thx-target=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:242
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListboxTarget()))
//line components/combobox.go:472
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thx-select=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:243
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListboxTarget()))
//line components/combobox.go:483
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thx-swap=\"outerHTML\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thx-sync=\"this:replace\"\n")
		}
//line components/combobox.kyse.go:246
		if kyse__d.Placeholder != "" {
//line components/combobox.go:496
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tplaceholder=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:247
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Placeholder))
//line components/combobox.go:503
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
//line components/combobox.kyse.go:249
		if kyse__d.DescribedBy() != "" {
//line components/combobox.go:511
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\taria-describedby=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:250
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.DescribedBy()))
//line components/combobox.go:518
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
//line components/combobox.kyse.go:252
		if kyse__d.Message() != "" {
//line components/combobox.go:526
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\taria-invalid=\"true\"\n")
			}
		}
//line components/combobox.kyse.go:255
		if kyse__d.Required {
//line components/combobox.go:533
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\trequired\n")
			}
		}
//line components/combobox.kyse.go:258
		if kyse__d.Disabled {
//line components/combobox.go:540
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdisabled\n")
			}
		}
//line components/combobox.kyse.go:261
		if kyse__d.Autofocus {
//line components/combobox.go:547
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tautofocus\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:266
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(icons.CaretDown(icons.Props{})))
//line components/combobox.go:564
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<div\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"panel\"\n")
		}
//line components/combobox.kyse.go:270
		if kyse__d.PartClass("panel") != "" {
//line components/combobox.go:580
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:271
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("panel")))
//line components/combobox.go:587
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-popover\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\taria-hidden=\"true\"\n")
		}
		if kyse__err == nil {
			var kyse__v6 string
//line components/combobox.kyse.go:275
			kyse__v6, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("panel"))
//line components/combobox.go:603
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:275", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<div\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"listbox\"\n")
		}
//line components/combobox.kyse.go:279
		if kyse__d.PartClass("listbox") != "" {
//line components/combobox.go:621
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:280
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("listbox")))
//line components/combobox.go:628
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\trole=\"listbox\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:283
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ListboxID()))
//line components/combobox.go:643
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\taria-orientation=\"vertical\"\n")
		}
		if kyse__err == nil {
			var kyse__v7 string
//line components/combobox.kyse.go:285
			kyse__v7, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("listbox"))
//line components/combobox.go:655
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:285", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v7)
			}
		}
//line components/combobox.kyse.go:286
		if kyse__d.EmptyText != "" {
//line components/combobox.go:664
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tdata-empty=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:287
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.EmptyText))
//line components/combobox.go:671
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>\n")
		}
//line components/combobox.kyse.go:290
		for at := 0; at < len(kyse__d.Options); at++ {
//line components/combobox.go:682
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t<div\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-part=\"option\"\n")
			}
//line components/combobox.kyse.go:293
			if kyse__d.PartClass("option") != "" {
//line components/combobox.go:691
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\tclass=\"")
				}
				if kyse__err == nil {
//line components/combobox.kyse.go:294
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("option")))
//line components/combobox.go:698
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\trole=\"option\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:297
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.OptionID(at)))
//line components/combobox.go:713
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-value=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:298
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Options[at].Value))
//line components/combobox.go:724
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-label=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:299
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Options[at].Text()))
//line components/combobox.go:735
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				var kyse__v8 string
//line components/combobox.kyse.go:300
				kyse__v8, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("option"))
//line components/combobox.go:744
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:300", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v8)
				}
			}
//line components/combobox.kyse.go:301
			if kyse__d.Options[at].Disabled {
//line components/combobox.go:753
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\taria-disabled=\"true\"\n")
				}
			}
//line components/combobox.kyse.go:304
			if kyse__d.Options[at].Value == kyse__d.Current() {
//line components/combobox.go:760
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\taria-selected=\"true\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t>")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:307
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Options[at].Text())))
//line components/combobox.go:771
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t</div>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</div>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<input type=\"hidden\" name=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:312
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/combobox.go:792
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" value=\"")
		}
		if kyse__err == nil {
//line components/combobox.kyse.go:312
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Current()))
//line components/combobox.go:800
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" data-combobox-value>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</div>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
//line components/combobox.kyse.go:315
		if kyse__d.Message() != "" {
//line components/combobox.go:813
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<p\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"message\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:318
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/combobox.go:826
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "-error\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:319
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("message", "text-destructive text-sm")))
//line components/combobox.go:837
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				var kyse__v9 string
//line components/combobox.kyse.go:320
				kyse__v9, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("message"))
//line components/combobox.go:846
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:320", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v9)
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
			}
			if kyse__err == nil {
//line components/combobox.kyse.go:321
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Message())))
//line components/combobox.go:859
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
			}
		}
//line components/combobox.kyse.go:323
		if kyse__d.Message() == "" {
//line components/combobox.go:867
//line components/combobox.kyse.go:324
			if kyse__d.Hint != "" {
//line components/combobox.go:870
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<p\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"hint\"\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tid=\"")
				}
				if kyse__err == nil {
//line components/combobox.kyse.go:327
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/combobox.go:883
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "-hint\"\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
				}
				if kyse__err == nil {
//line components/combobox.kyse.go:328
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("hint", "text-muted-foreground text-sm")))
//line components/combobox.go:894
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
				if kyse__err == nil {
					var kyse__v10 string
//line components/combobox.kyse.go:329
					kyse__v10, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("hint"))
//line components/combobox.go:903
					if kyse__err != nil {
						kyse__err = kyse__fmt.Errorf("%s: %w", "components/combobox.kyse.go:329", kyse__err)
					} else {
						_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v10)
					}
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
				}
				if kyse__err == nil {
//line components/combobox.kyse.go:330
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Hint)))
//line components/combobox.go:916
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
				}
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
