// Code generated by `aru view:build` from command.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/icons"
	"strconv"
)

//line components/command.kyse.go:11

// CommandProps is the palette: everywhere a screen can go, in one list, with a
// box that narrows it.
//
// # Where the filtering happens
//
// In the browser, and nowhere else: a palette holds the places one application
// has, which is a list the page can carry whole, and asking a server between
// two keystrokes to re-sort thirty lines somebody is looking straight at is a
// round trip they would feel.
//
// The list is drawn once and every line stays in the document. Narrowing marks
// the lines that do not match hidden, which is also what empties a group whose
// lines all went, and what puts EmptyText on the screen when none are left.
// Nothing is fetched, so nothing arrives late and nothing arrives out of order.
//
// Two attributes carry that, and they are data on both sides: data-search is
// what a line is matched against, and aria-hidden is what the match writes. The
// stylesheet reads the second one and does the hiding, the emptying and the
// message. Nothing on this page is an expression somebody's browser evaluates.
//
// # What a line is
//
// A link. It is reachable by tab, opens in a new tab on the modifier somebody
// already uses, and goes where it says it goes with the palette's own keyboard
// switched off entirely. A line with no URL is drawn without one, which is an
// anchor the browser will not focus or follow, and is marked disabled so it is
// announced the way it looks.
type CommandProps struct {
	// ID is the id everything inside is hung off. Two palettes on one page
	// need two of them.
	ID string
	// Label is what assistive technology calls the palette as a whole.
	Label string
	// Placeholder is the grey text inside the empty search box.
	Placeholder string
	// EmptyText is the sentence drawn in place of the list when nothing
	// matched. Empty takes the stylesheet's own wording.
	EmptyText string
	// Groups are the lines, in the order they are read, under the headings
	// they belong to. A group whose lines all fail the search draws neither
	// its heading nor a gap.
	Groups []CommandGroup
}

// CommandGroup is one heading and the lines under it.
type CommandGroup struct {
	// Heading is the small line over the group. Empty draws none, which is
	// right for a palette with one group and wrong for a palette with three.
	Heading string
	// Items are the lines.
	Items []CommandItem
}

// CommandItem is one line of the palette.
type CommandItem struct {
	// Label is what the line reads as, and what the search matches first.
	Label string
	// Keywords are the other words that should find this line: what somebody
	// calls it when they do not call it what it is called. They are matched
	// and never shown.
	Keywords string
	// Shortcut is the key combination drawn at the end of the line. It is
	// shown and never bound: what the keys do is the application's, and a
	// component that bound them would take a combination the page already
	// uses.
	Shortcut string
	// URL is where the line goes. Empty draws the line as unavailable.
	URL string
	// Disabled draws the line as unavailable while leaving it in the list, so
	// that what exists but cannot be reached is still visible.
	Disabled bool
}

// Available reports whether this line can be followed.
func (i CommandItem) Available() bool {
	return i.URL != "" && !i.Disabled
}

// Search is what this line is matched against: what it reads as, and the words
// somebody might look for it under.
func (i CommandItem) Search() string {
	if i.Keywords == "" {
		return i.Label
	}
	return i.Label + " " + i.Keywords
}

// InputID names the search box.
func (p CommandProps) InputID() string {
	return p.ID + "-input"
}

// MenuID names the list, which is what the search box says it controls.
func (p CommandProps) MenuID() string {
	return p.ID + "-menu"
}

// HeadingID names a group's heading, so the group is announced by it.
func (p CommandProps) HeadingID(group int) string {
	return p.ID + "-heading-" + strconv.Itoa(group)
}

// ItemID names one line.
//
// It is numbered rather than named after the line, because
// aria-activedescendant holds an id and an id with a space in it is read as
// two.
func (p CommandProps) ItemID(group, item int) string {
	return p.ID + "-item-" + strconv.Itoa(group) + "-" + strconv.Itoa(item)
}

//line components/command.go:132

// Command renders the command component.
func Command(kyse__props CommandProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div class=\"command\" id=\"")
	}
	if kyse__err == nil {
//line components/command.kyse.go:124
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/command.go:151
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
//line components/command.kyse.go:125
	if kyse__d.Label != "" {
//line components/command.go:158
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-label=\"")
		}
		if kyse__err == nil {
//line components/command.kyse.go:126
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Label))
//line components/command.go:165
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-command\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t")
	}
	if kyse__err == nil {
//line components/command.kyse.go:131
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.UnsafeText(icons.MagnifyingGlass(icons.Props{})))
//line components/command.go:186
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<input\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\ttype=\"text\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\trole=\"combobox\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tid=\"")
	}
	if kyse__err == nil {
//line components/command.kyse.go:135
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.InputID()))
//line components/command.go:206
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tautocomplete=\"off\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tautocorrect=\"off\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tspellcheck=\"false\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-autocomplete=\"list\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-expanded=\"true\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-controls=\"")
	}
	if kyse__err == nil {
//line components/command.kyse.go:141
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.MenuID()))
//line components/command.go:232
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
//line components/command.kyse.go:142
	if kyse__d.Placeholder != "" {
//line components/command.go:239
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tplaceholder=\"")
		}
		if kyse__err == nil {
//line components/command.kyse.go:143
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Placeholder))
//line components/command.go:246
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div role=\"menu\" id=\"")
	}
	if kyse__err == nil {
//line components/command.kyse.go:148
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.MenuID()))
//line components/command.go:267
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\" aria-orientation=\"vertical\"\n")
	}
//line components/command.kyse.go:149
	if kyse__d.EmptyText != "" {
//line components/command.go:274
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-empty=\"")
		}
		if kyse__err == nil {
//line components/command.kyse.go:150
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.EmptyText))
//line components/command.go:281
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
//line components/command.kyse.go:153
	for g := 0; g < len(kyse__d.Groups); g++ {
//line components/command.go:292
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<div role=\"group\"\n")
		}
//line components/command.kyse.go:155
		if kyse__d.Groups[g].Heading != "" {
//line components/command.go:298
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\taria-labelledby=\"")
			}
			if kyse__err == nil {
//line components/command.kyse.go:156
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.HeadingID(g)))
//line components/command.go:305
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>\n")
		}
//line components/command.kyse.go:159
		if kyse__d.Groups[g].Heading != "" {
//line components/command.go:316
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<span role=\"heading\" id=\"")
			}
			if kyse__err == nil {
//line components/command.kyse.go:160
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.HeadingID(g)))
//line components/command.go:323
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\">")
			}
			if kyse__err == nil {
//line components/command.kyse.go:160
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Groups[g].Heading)))
//line components/command.go:331
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
//line components/command.kyse.go:163
		for i := 0; i < len(kyse__d.Groups[g].Items); i++ {
//line components/command.go:342
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<a\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\trole=\"menuitem\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/command.kyse.go:166
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ItemID(g, i)))
//line components/command.go:355
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tdata-search=\"")
			}
			if kyse__err == nil {
//line components/command.kyse.go:167
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Groups[g].Items[i].Search()))
//line components/command.go:366
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
//line components/command.kyse.go:168
			if kyse__d.Groups[g].Items[i].Available() {
//line components/command.go:373
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\thref=\"")
				}
				if kyse__err == nil {
					var kyse__v1 string
//line components/command.kyse.go:169
					kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.Groups[g].Items[i].URL)
//line components/command.go:381
					if kyse__err != nil {
						kyse__err = kyse__fmt.Errorf("%s: %w", "components/command.kyse.go:169", kyse__err)
					} else {
						_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
					}
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
//line components/command.kyse.go:171
			if !kyse__d.Groups[g].Items[i].Available() {
//line components/command.go:394
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\taria-disabled=\"true\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t<span>")
			}
			if kyse__err == nil {
//line components/command.kyse.go:175
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Groups[g].Items[i].Label)))
//line components/command.go:408
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
			}
//line components/command.kyse.go:176
			if kyse__d.Groups[g].Items[i].Shortcut != "" {
//line components/command.go:415
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t<span data-shortcut>")
				}
				if kyse__err == nil {
//line components/command.kyse.go:177
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Groups[g].Items[i].Shortcut)))
//line components/command.go:422
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t</a>\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</div>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__view.UnsafeText
	_ = kyse__strings.Builder{}
)
