// Code generated by `aru view:build` from dialog.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"strings"
)

//line components/dialog.kyse.go:7

// DialogProps is a confirmation: the thing about to happen, and the two ways
// out of it.
//
// It is a <dialog>, so the browser handles the backdrop, the focus trap and
// Escape. That is four behaviours nobody has to write, and the four that
// hand-built modals get wrong.
//
// None of the four is true unless it was opened with showModal(). One opened by
// setting the open attribute is not modal: the page behind it stays reachable,
// focus walks out of it, and Escape does nothing. And a modal dialog never
// closes on a click outside itself, which is the behaviour a confirmation
// wants and is not something this has to arrange.
//
// It confirms rather than composes. A dialog that could hold anything would
// have to take markup as a string, which is where escaping stops being
// guaranteed -- and "are you sure" is what a dialog is for nine times in ten.
type DialogProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// ID is what a button targets to open this: `onclick="ID.showModal()"`.
	ID string
	// Title is the question.
	Title string
	// Message is the consequence, spelled out. A destructive dialog that does
	// not say what is lost is a dialog people dismiss without reading.
	Message string

	// ConfirmLabel is the button that goes through with it. Empty means
	// "Confirm".
	ConfirmLabel string
	// ConfirmVariant styles it. Use "destructive" for anything that deletes.
	ConfirmVariant string
	// Action and Method are the form the confirm button submits. PUT, PATCH and
	// DELETE are carried by a POST with a hidden _method field, because browsers
	// cannot submit those methods directly. A dialog that deletes over GET is a
	// dialog a crawler can fire.
	Action string
	Method string

	// CancelLabel is the way out. Empty means "Cancel".
	CancelLabel string

	// Alert draws this as an alert dialog instead: the message is announced
	// along with the title the moment it opens, and the cursor starts on the
	// way out rather than on the way through. Use it for what cannot be undone.
	//
	// It is a field rather than a component of its own because the two differ
	// in the role, in what is announced and in where focus lands, and in
	// nothing else -- the question, the consequence and the pair of buttons are
	// the same markup. Two components would be two ways to ask "are you sure",
	// and within a year they would answer it differently.
	Alert bool

	// Token is the CSRF token. It is passed in rather than read from the page,
	// because a component does not receive the page.
	Token string
}

// Surface is the stylesheet this is drawn on: the alert one is wider, centres
// its heading on a narrow screen and has room for a figure above it.
func (p DialogProps) Surface() string {
	if p.Alert {
		return "alert-dialog"
	}
	return "dialog"
}

// DescribedBy names the consequence, and is empty when there is none. An
// aria-describedby pointing at an element that was never drawn describes
// nothing, which is worse than describing nothing at all: it reads as a
// description that failed to arrive.
func (p DialogProps) DescribedBy() string {
	if p.Message == "" {
		return ""
	}
	return p.ID + "-description"
}

// Confirm is the label of the button that goes through with it.
func (p DialogProps) Confirm() string {
	if p.ConfirmLabel == "" {
		return "Confirm"
	}
	return p.ConfirmLabel
}

// Cancel is the label of the way out.
func (p DialogProps) Cancel() string {
	if p.CancelLabel == "" {
		return "Cancel"
	}
	return p.CancelLabel
}

// FormMethod is the method a browser submits. It defaults to post because
// everything a dialog confirms changes something, and uses post as the carrier
// for PUT, PATCH and DELETE.
func (p DialogProps) FormMethod() string {
	if p.Method == "" {
		return "post"
	}
	if p.MethodOverride() != "" {
		return "post"
	}
	return strings.ToLower(p.Method)
}

// MethodOverride is the method carried in the hidden _method field, or empty
// when the browser can submit the requested method directly.
func (p DialogProps) MethodOverride() string {
	method := strings.ToUpper(p.Method)
	switch method {
	case "PUT", "PATCH", "DELETE":
		return method
	default:
		return ""
	}
}

// PartNames are the parts this component publishes.
func (p DialogProps) PartNames() []string {
	return []string{"root", "content", "header", "title", "message", "footer", "cancel", "confirm"}
}

//line components/dialog.go:144

// Dialog renders the dialog component.
func Dialog(kyse__props DialogProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<dialog\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tid=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:134
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/dialog.go:169
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:135
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass(kyse__d.Surface())))
//line components/dialog.go:180
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\taria-labelledby=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:136
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/dialog.go:191
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "-title\"\n")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/dialog.kyse.go:137
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/dialog.go:200
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:137", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
//line components/dialog.kyse.go:138
	if kyse__d.Alert {
//line components/dialog.go:209
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\trole=\"alertdialog\"\n")
		}
	}
//line components/dialog.kyse.go:141
	if kyse__d.DescribedBy() != "" {
//line components/dialog.go:216
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-describedby=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:142
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.DescribedBy()))
//line components/dialog.go:223
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<article\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"content\"\n")
	}
//line components/dialog.kyse.go:147
	if kyse__d.PartClass("content") != "" {
//line components/dialog.go:240
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:148
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("content")))
//line components/dialog.go:247
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v2 string
//line components/dialog.kyse.go:150
		kyse__v2, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("content"))
//line components/dialog.go:257
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:150", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<header\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"header\"\n")
	}
//line components/dialog.kyse.go:154
	if kyse__d.PartClass("header") != "" {
//line components/dialog.go:275
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:155
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("header")))
//line components/dialog.go:282
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v3 string
//line components/dialog.kyse.go:157
		kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("header"))
//line components/dialog.go:292
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:157", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<h2\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"title\"\n")
	}
//line components/dialog.kyse.go:161
	if kyse__d.PartClass("title") != "" {
//line components/dialog.go:310
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:162
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("title")))
//line components/dialog.go:317
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:164
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/dialog.go:329
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "-title\"\n")
	}
	if kyse__err == nil {
		var kyse__v4 string
//line components/dialog.kyse.go:165
		kyse__v4, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("title"))
//line components/dialog.go:338
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:165", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:166
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line components/dialog.go:351
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</h2>\n")
	}
//line components/dialog.kyse.go:167
	if kyse__d.Message != "" {
//line components/dialog.go:358
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<p\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"message\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:170
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/dialog.go:371
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "-description\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:171
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("message", "text-muted-foreground text-sm")))
//line components/dialog.go:382
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v5 string
//line components/dialog.kyse.go:172
			kyse__v5, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("message"))
//line components/dialog.go:391
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:172", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v5)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:173
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Message)))
//line components/dialog.go:404
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<footer\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"footer\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:179
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("footer", "flex justify-end gap-2")))
//line components/dialog.go:428
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v6 string
//line components/dialog.kyse.go:180
		kyse__v6, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("footer"))
//line components/dialog.go:437
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:180", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<form method=\"dialog\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<button\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"cancel\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\ttype=\"submit\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:186
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("cancel", "btn")))
//line components/dialog.go:465
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-variant=\"outline\"\n")
	}
	if kyse__err == nil {
		var kyse__v7 string
//line components/dialog.kyse.go:188
		kyse__v7, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("cancel"))
//line components/dialog.go:477
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:188", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v7)
		}
	}
//line components/dialog.kyse.go:189
	if kyse__d.Alert {
//line components/dialog.go:486
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tautofocus\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:192
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Cancel())))
//line components/dialog.go:497
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</form>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<form method=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:194
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.FormMethod()))
//line components/dialog.go:511
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\" action=\"")
	}
	if kyse__err == nil {
		var kyse__v8 string
//line components/dialog.kyse.go:194
		kyse__v8, kyse__err = kyse__view.TextURL(kyse__d.Action)
//line components/dialog.go:520
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:194", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v8)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
//line components/dialog.kyse.go:195
	if kyse__d.MethodOverride() != "" {
//line components/dialog.go:532
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<input type=\"hidden\" name=\"_method\" value=\"")
		}
		if kyse__err == nil {
//line components/dialog.kyse.go:196
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.MethodOverride()))
//line components/dialog.go:539
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<input type=\"hidden\" name=\"_token\" value=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:198
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Token))
//line components/dialog.go:551
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<button\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"confirm\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\ttype=\"submit\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:202
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("confirm", "btn")))
//line components/dialog.go:571
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-variant=\"")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:203
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ConfirmVariant))
//line components/dialog.go:582
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v9 string
//line components/dialog.kyse.go:204
		kyse__v9, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("confirm"))
//line components/dialog.go:591
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/dialog.kyse.go:204", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v9)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
	}
	if kyse__err == nil {
//line components/dialog.kyse.go:205
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Confirm())))
//line components/dialog.go:604
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</form>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</footer>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</article>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</dialog>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
