// Package components draws the pieces a screen is made of.
//
// Every component is an exported function taking its own props and returning
// template.HTML, so a view interpolates it:
//
//	{!! components.Button(components.ButtonProps{Label: "Save"}) !!}
//
// That shape is the reason this package exists rather than a directory of files
// copied into each project. The Go compiler resolves the name and checks the
// props, so a component that does not exist and a field that does not exist are
// both build errors, reported at the line of the .kyse.go somebody wrote. A
// component library resolved by name at run time reports the same two mistakes
// as a blank space and a 500.
//
// The .kyse.go files beside each .go are the sources. The .go are generated by
// `aru view:build`, run from the root of this module, and are committed --
// a module whose generated files are missing is a module `go get` cannot use.
//
// The class names are semantic -- btn, field, card -- and the rules behind them
// ship with the skeleton under resources/css/basecoat/. The same button written
// with utility classes is 443 characters of markup; this way it is thirty.
package components
