// Code generated by `aru view:build` from drawer.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line components/drawer.kyse.go:5

// DrawerProps is a panel that comes in from an edge of the screen, carrying the
// places to go from here.
//
// It is a <dialog>, and that is where its behaviour comes from rather than from
// anything written here. Opened with showModal(), the rest of the document is
// inert, focus cannot leave the panel while it is open, Escape closes it, and
// closing puts focus back on whatever opened it. Four behaviours, none of them
// written, and the four that hand-built panels get wrong.
//
// # What it does not do
//
// It does not open itself, and the way it is opened decides whether any of the
// above is true. A trigger calls showModal() on it. A panel whose open
// attribute is set instead is not modal at all: the page behind it stays
// reachable, focus walks straight out of it, and Escape does nothing.
//
// It does not close when the backdrop is clicked. A modal dialog never does on
// its own, and the click handler that would add it is a script this library
// does not ship.
//
// It slides in and it does not slide out. The stylesheet starts the entry
// transition by itself; the exit needs an attribute set at the moment of
// closing and removed when the transition ends, and that is a script as well.
// The panel disappears rather than leaving.
//
// It carries destinations rather than arbitrary content, for the reason a card
// does: content would have to arrive as a string of HTML, and a string of HTML
// is where escaping stops being guaranteed by construction. A panel that has to
// hold a form is written as <dialog class="drawer"> directly.
type DrawerProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// ID is what a trigger targets to open this:
	//
	//	<button data-dialog-open="ID">Filters</button>
	//
	// Not an inline onclick. The policy this framework serves under is
	// script-src 'self' with no 'unsafe-inline', and that blocks an inline
	// handler exactly as it blocks an inline script -- so the handler works
	// while somebody is building and fails when the headers go on. The
	// attribute is read by the shipped script, which looks the id up and
	// never evaluates anything.
	ID string
	// Side is the edge it comes in from: "left", "right", "top" or "bottom".
	// Empty is the bottom, because that is what the stylesheet draws when
	// nothing says otherwise.
	Side string
	// Title is the heading, and the name assistive technology announces when
	// the panel opens.
	Title string
	// Description is the sentence under the title, and may be empty.
	Description string
	// Links are the destinations, drawn in the order they are given. None
	// draws the header and the footer with nothing between them.
	Links []DrawerLink
	// CloseLabel is the button that shuts it. Empty means "Close".
	CloseLabel string
}

// DrawerLink is one destination in a drawer.
type DrawerLink struct {
	// Label is the text.
	Label string
	// Href is where it goes.
	Href string
	// Current marks this as the page already being shown. It is what tells
	// somebody who cannot see the highlight where in the list they are.
	Current bool
}

// Close is the label of the button that shuts the panel.
func (p DrawerProps) Close() string {
	if p.CloseLabel == "" {
		return "Close"
	}
	return p.CloseLabel
}

// DescribedBy names the sentence under the title, and is empty when there is
// none. An aria-describedby pointing at an element that was never drawn
// describes nothing, and reads as a panel whose description failed to load.
func (p DrawerProps) DescribedBy() string {
	if p.Description == "" {
		return ""
	}
	return p.ID + "-description"
}

// PartNames are the parts this component publishes.
func (p DrawerProps) PartNames() []string {
	return []string{"root", "content", "header", "title", "description", "nav", "link", "footer", "close"}
}

//line components/drawer.go:112

// Drawer renders the drawer component.
func Drawer(kyse__props DrawerProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<dialog\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tid=\"")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:101
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/drawer.go:137
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:102
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("drawer")))
//line components/drawer.go:148
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\taria-labelledby=\"")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:103
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/drawer.go:159
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "-title\"\n")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/drawer.kyse.go:104
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/drawer.go:168
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:104", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
//line components/drawer.kyse.go:105
	if kyse__d.Side != "" {
//line components/drawer.go:177
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-side=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:106
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Side))
//line components/drawer.go:184
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/drawer.kyse.go:108
	if kyse__d.DescribedBy() != "" {
//line components/drawer.go:192
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-describedby=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:109
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.DescribedBy()))
//line components/drawer.go:199
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<article\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"content\"\n")
	}
//line components/drawer.kyse.go:114
	if kyse__d.PartClass("content") != "" {
//line components/drawer.go:216
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:115
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("content")))
//line components/drawer.go:223
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v2 string
//line components/drawer.kyse.go:117
		kyse__v2, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("content"))
//line components/drawer.go:233
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:117", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<header\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"header\"\n")
	}
//line components/drawer.kyse.go:121
	if kyse__d.PartClass("header") != "" {
//line components/drawer.go:251
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:122
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("header")))
//line components/drawer.go:258
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v3 string
//line components/drawer.kyse.go:124
		kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("header"))
//line components/drawer.go:268
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:124", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<h2\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"title\"\n")
	}
//line components/drawer.kyse.go:128
	if kyse__d.PartClass("title") != "" {
//line components/drawer.go:286
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:129
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("title")))
//line components/drawer.go:293
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:131
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/drawer.go:305
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "-title\"\n")
	}
	if kyse__err == nil {
		var kyse__v4 string
//line components/drawer.kyse.go:132
		kyse__v4, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("title"))
//line components/drawer.go:314
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:132", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:133
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line components/drawer.go:327
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</h2>\n")
	}
//line components/drawer.kyse.go:134
	if kyse__d.Description != "" {
//line components/drawer.go:334
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<p\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"description\"\n")
		}
//line components/drawer.kyse.go:137
		if kyse__d.PartClass("description") != "" {
//line components/drawer.go:343
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/drawer.kyse.go:138
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("description")))
//line components/drawer.go:350
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:140
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/drawer.go:362
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "-description\"\n")
		}
		if kyse__err == nil {
			var kyse__v5 string
//line components/drawer.kyse.go:141
			kyse__v5, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("description"))
//line components/drawer.go:371
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:141", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v5)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:142
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Description)))
//line components/drawer.go:384
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
//line components/drawer.kyse.go:146
	if len(kyse__d.Links) > 0 {
//line components/drawer.go:398
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<section class=\"p-4\">\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<nav\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"nav\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:150
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("nav", "grid gap-1")))
//line components/drawer.go:414
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v6 string
//line components/drawer.kyse.go:151
			kyse__v6, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("nav"))
//line components/drawer.go:423
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:151", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>\n")
		}
//line components/drawer.kyse.go:153
		for _, link := range kyse__d.Links {
			_ = link
//line components/drawer.go:436
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t<a\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-part=\"link\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/drawer.kyse.go:156
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("link", "btn justify-start")))
//line components/drawer.go:449
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-variant=\"ghost\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\thref=\"")
			}
			if kyse__err == nil {
				var kyse__v7 string
//line components/drawer.kyse.go:158
				kyse__v7, kyse__err = kyse__view.TextURL(link.Href)
//line components/drawer.go:464
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:158", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v7)
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				var kyse__v8 string
//line components/drawer.kyse.go:159
				kyse__v8, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("link"))
//line components/drawer.go:478
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:159", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v8)
				}
			}
//line components/drawer.kyse.go:160
			if link.Current {
//line components/drawer.go:487
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\taria-current=\"page\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t>")
			}
			if kyse__err == nil {
//line components/drawer.kyse.go:163
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(link.Label)))
//line components/drawer.go:498
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</a>\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t</nav>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</section>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<footer\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"footer\"\n")
	}
//line components/drawer.kyse.go:171
	if kyse__d.PartClass("footer") != "" {
//line components/drawer.go:522
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/drawer.kyse.go:172
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("footer")))
//line components/drawer.go:529
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v9 string
//line components/drawer.kyse.go:174
		kyse__v9, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("footer"))
//line components/drawer.go:539
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:174", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v9)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<form method=\"dialog\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<button\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"close\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\ttype=\"submit\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:180
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("close", "btn")))
//line components/drawer.go:567
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-variant=\"outline\"\n")
	}
	if kyse__err == nil {
		var kyse__v10 string
//line components/drawer.kyse.go:182
		kyse__v10, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("close"))
//line components/drawer.go:579
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/drawer.kyse.go:182", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v10)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
	}
	if kyse__err == nil {
//line components/drawer.kyse.go:183
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Close())))
//line components/drawer.go:592
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</form>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</footer>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</article>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</dialog>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
