// Code generated by `aru view:build` from dropdown-menu.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/framework/view"
	"strconv"
)

//line components/dropdown-menu.kyse.go:7

// DropdownMenuProps is a button and the list of things it opens.
//
// The three parts each carry the name of another: the trigger says which menu
// it controls, the menu says which trigger labels it, and the panel between
// them is what is shown and hidden. Written out by hand that is four ids and
// five attributes, and the one people leave out is aria-expanded -- which is
// the only part that says whether the menu is open at all.
//
// It is a menu rather than a list of links in a box, and the difference is what
// the keyboard does: the arrow keys walk the entries, Home and End reach the
// ends, Escape closes it and hands focus back to the trigger, and a click
// anywhere else closes it. Focus stays on the trigger the whole time and the
// entry the arrows have reached is named by aria-activedescendant, which is why
// every entry is numbered here -- an entry with no id is highlighted and not
// announced, which is the half of the behaviour nobody sees go missing.
//
// A separator and a heading are announced as what they are, so a group of five
// entries is not read as five of nine.
//
// Entries are values rather than markup. A menu is a list of choices, and one
// that could hold anything would have to take a string of HTML -- which is
// where escaping stops being guaranteed by construction.
type DropdownMenuProps struct {
	// ID is what the trigger, the panel, the menu and every entry hang their
	// ids off. Two menus on one page need two.
	ID string
	// Label is the text on the trigger.
	Label string
	// Variant and Size style the trigger. Empty is the default of each.
	Variant string
	Size    string
	// Items are the entries, separators and headings, in the order they read.
	Items []MenuItem
	// Side is which way the panel opens: "top", "bottom", "left", "right", or
	// the logical "inline-start" and "inline-end", which turn around in a
	// right-to-left document. Empty opens downward.
	Side string
	// Align is where the panel sits along that side: "start", "end" or
	// "center". Empty aligns it to the start.
	Align string
}

// MenuItem is one line of the menu.
//
// Separator and Heading are what a line is instead of an entry, and they are
// read in that order: a separator carries no text, a heading is text that
// cannot be chosen, and everything else is a choice.
type MenuItem struct {
	// Label is the text.
	Label string
	// URL makes the entry a link. Empty makes it a button, which is what an
	// entry that acts rather than navigates is.
	URL string
	// Variant is "destructive" for the entry that deletes something. It is the
	// one entry a menu should not draw like the others.
	Variant string
	// Shortcut is the key combination shown down the far side. It is a reminder
	// of a binding the page already has, and drawing it does not create one.
	Shortcut string
	// Heading draws the line as the title of the group under it.
	Heading bool
	// Separator draws the line as a rule between groups.
	Separator bool
	// Disabled draws the entry unavailable, and the arrow keys pass over it.
	Disabled bool

	// The HTMX attributes, written only when they carry something. An empty
	// hx-post is an attribute HTMX acts on: it would post to the current URL.
	HxPost    string
	HxGet     string
	HxTarget  string
	HxConfirm string
}

// TriggerID is the id of the button that opens the menu.
func (p DropdownMenuProps) TriggerID() string { return p.ID + "-trigger" }

// PanelID is the id of the box that is shown and hidden.
func (p DropdownMenuProps) PanelID() string { return p.ID + "-popover" }

// MenuID is the id of the list of entries inside it.
func (p DropdownMenuProps) MenuID() string { return p.ID + "-menu" }

// ItemID is the id of the entry at a position, which is what
// aria-activedescendant points at while the arrow keys are on it.
//
// It is numbered rather than taken from the entry, because the entry has
// nothing unique on it: two menus commonly hold two entries reading "Delete",
// and an id repeated is an announcement naming the wrong line.
func (p DropdownMenuProps) ItemID(at int) string { return p.ID + "-item-" + strconv.Itoa(at) }

//line components/dropdown-menu.go:111

// DropdownMenu renders the dropdown-menu component.
func DropdownMenu(kyse__props DropdownMenuProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div class=\"dropdown-menu\" id=\"")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:100
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/dropdown-menu.go:130
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<button\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\ttype=\"button\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"btn\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:104
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.TriggerID()))
//line components/dropdown-menu.go:150
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-haspopup=\"menu\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-controls=\"")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:106
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.MenuID()))
//line components/dropdown-menu.go:164
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-expanded=\"false\"\n")
	}
//line components/dropdown-menu.kyse.go:108
	if kyse__d.Variant != "" {
//line components/dropdown-menu.go:174
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-variant=\"")
		}
		if kyse__err == nil {
//line components/dropdown-menu.kyse.go:109
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Variant))
//line components/dropdown-menu.go:181
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/dropdown-menu.kyse.go:111
	if kyse__d.Size != "" {
//line components/dropdown-menu.go:189
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-size=\"")
		}
		if kyse__err == nil {
//line components/dropdown-menu.kyse.go:112
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Size))
//line components/dropdown-menu.go:196
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:114
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Label)))
//line components/dropdown-menu.go:208
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:117
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PanelID()))
//line components/dropdown-menu.go:225
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-popover\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-hidden=\"true\"\n")
	}
//line components/dropdown-menu.kyse.go:120
	if kyse__d.Side != "" {
//line components/dropdown-menu.go:238
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-side=\"")
		}
		if kyse__err == nil {
//line components/dropdown-menu.kyse.go:121
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Side))
//line components/dropdown-menu.go:245
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/dropdown-menu.kyse.go:123
	if kyse__d.Align != "" {
//line components/dropdown-menu.go:253
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-align=\"")
		}
		if kyse__err == nil {
//line components/dropdown-menu.kyse.go:124
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Align))
//line components/dropdown-menu.go:260
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<div role=\"menu\" id=\"")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:127
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.MenuID()))
//line components/dropdown-menu.go:275
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\" aria-labelledby=\"")
	}
	if kyse__err == nil {
//line components/dropdown-menu.kyse.go:127
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.TriggerID()))
//line components/dropdown-menu.go:283
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
//line components/dropdown-menu.kyse.go:128
	for at := 0; at < len(kyse__d.Items); at++ {
//line components/dropdown-menu.go:290
//line components/dropdown-menu.kyse.go:129
		if kyse__d.Items[at].Separator {
//line components/dropdown-menu.go:293
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<hr role=\"separator\">\n")
			}
//line components/dropdown-menu.kyse.go:131
		} else if kyse__d.Items[at].Heading {
//line components/dropdown-menu.go:299
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<div role=\"heading\" id=\"")
			}
			if kyse__err == nil {
//line components/dropdown-menu.kyse.go:132
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ItemID(at)))
//line components/dropdown-menu.go:306
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\">")
			}
			if kyse__err == nil {
//line components/dropdown-menu.kyse.go:132
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Items[at].Label)))
//line components/dropdown-menu.go:314
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
			}
//line components/dropdown-menu.kyse.go:133
		} else if kyse__d.Items[at].URL != "" {
//line components/dropdown-menu.go:321
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<a\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\trole=\"menuitem\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/dropdown-menu.kyse.go:136
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ItemID(at)))
//line components/dropdown-menu.go:334
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\thref=\"")
			}
			if kyse__err == nil {
				var kyse__v1 string
//line components/dropdown-menu.kyse.go:137
				kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.Items[at].URL)
//line components/dropdown-menu.go:346
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/dropdown-menu.kyse.go:137", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
//line components/dropdown-menu.kyse.go:138
			if kyse__d.Items[at].Variant != "" {
//line components/dropdown-menu.go:358
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-variant=\"")
				}
				if kyse__err == nil {
//line components/dropdown-menu.kyse.go:139
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Items[at].Variant))
//line components/dropdown-menu.go:365
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
//line components/dropdown-menu.kyse.go:141
			if kyse__d.Items[at].Disabled {
//line components/dropdown-menu.go:373
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\taria-disabled=\"true\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t")
			}
			if kyse__err == nil {
//line components/dropdown-menu.kyse.go:145
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Items[at].Label)))
//line components/dropdown-menu.go:387
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
			}
//line components/dropdown-menu.kyse.go:146
			if kyse__d.Items[at].Shortcut != "" {
//line components/dropdown-menu.go:394
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t<kbd>")
				}
				if kyse__err == nil {
//line components/dropdown-menu.kyse.go:147
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Items[at].Shortcut)))
//line components/dropdown-menu.go:401
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "</kbd>\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t</a>\n")
			}
		} else {
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<button\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\ttype=\"button\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\trole=\"menuitem\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/dropdown-menu.kyse.go:154
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ItemID(at)))
//line components/dropdown-menu.go:426
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
//line components/dropdown-menu.kyse.go:155
			if kyse__d.Items[at].Variant != "" {
//line components/dropdown-menu.go:433
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\tdata-variant=\"")
				}
				if kyse__err == nil {
//line components/dropdown-menu.kyse.go:156
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Items[at].Variant))
//line components/dropdown-menu.go:440
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
//line components/dropdown-menu.kyse.go:158
			if kyse__d.Items[at].Disabled {
//line components/dropdown-menu.go:448
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\taria-disabled=\"true\"\n")
				}
			}
//line components/dropdown-menu.kyse.go:161
			if kyse__d.Items[at].HxPost != "" {
//line components/dropdown-menu.go:455
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\thx-post=\"")
				}
				if kyse__err == nil {
					var kyse__v2 string
//line components/dropdown-menu.kyse.go:162
					kyse__v2, kyse__err = kyse__view.TextURL(kyse__d.Items[at].HxPost)
//line components/dropdown-menu.go:463
					if kyse__err != nil {
						kyse__err = kyse__fmt.Errorf("%s: %w", "components/dropdown-menu.kyse.go:162", kyse__err)
					} else {
						_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
					}
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
//line components/dropdown-menu.kyse.go:164
			if kyse__d.Items[at].HxGet != "" {
//line components/dropdown-menu.go:476
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\thx-get=\"")
				}
				if kyse__err == nil {
					var kyse__v3 string
//line components/dropdown-menu.kyse.go:165
					kyse__v3, kyse__err = kyse__view.TextURL(kyse__d.Items[at].HxGet)
//line components/dropdown-menu.go:484
					if kyse__err != nil {
						kyse__err = kyse__fmt.Errorf("%s: %w", "components/dropdown-menu.kyse.go:165", kyse__err)
					} else {
						_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
					}
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
//line components/dropdown-menu.kyse.go:167
			if kyse__d.Items[at].HxTarget != "" {
//line components/dropdown-menu.go:497
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\thx-target=\"")
				}
				if kyse__err == nil {
//line components/dropdown-menu.kyse.go:168
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Items[at].HxTarget))
//line components/dropdown-menu.go:504
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
//line components/dropdown-menu.kyse.go:170
			if kyse__d.Items[at].HxConfirm != "" {
//line components/dropdown-menu.go:512
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\thx-confirm=\"")
				}
				if kyse__err == nil {
//line components/dropdown-menu.kyse.go:171
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Items[at].HxConfirm))
//line components/dropdown-menu.go:519
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t")
			}
			if kyse__err == nil {
//line components/dropdown-menu.kyse.go:174
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Items[at].Label)))
//line components/dropdown-menu.go:534
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
			}
//line components/dropdown-menu.kyse.go:175
			if kyse__d.Items[at].Shortcut != "" {
//line components/dropdown-menu.go:541
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t<kbd>")
				}
				if kyse__err == nil {
//line components/dropdown-menu.kyse.go:176
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Items[at].Shortcut)))
//line components/dropdown-menu.go:548
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "</kbd>\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t</button>\n")
			}
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__view.UnsafeText
	_ = kyse__strings.Builder{}
)
