// Code generated by `aru view:build` from hover-card.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line components/hover-card.kyse.go:5

// HoverCardProps is a preview of what is behind a link, shown when the pointer
// rests on it or the keyboard focuses it.
//
// It is a preview and never the only way to reach something. Everything in the
// card is also behind the link, because a card that appears on hover is a card
// that never appears on a touch screen -- there is no hover there, and there
// never will be. So the link works, and this is what a pointer gets in
// addition.
//
// It draws its own trigger, for the same reason a tooltip does: the card has
// to be part of the same hover target as the link, or it vanishes while the
// pointer is travelling to it.
//
// It publishes root, trigger, content, avatar, title, subtitle, description
// and meta.
type HoverCardProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// ID is what the trigger and the card use to point at each other.
	ID string
	// Label is the text of the link.
	Label string
	// URL is where the link goes. The card previews it; the link reaches it.
	URL string
	// Title is the heading inside the card. Empty uses the label.
	Title string
	// Subtitle is the smaller line under it: a handle, a role, a date.
	Subtitle string
	// Description is the sentence.
	Description string
	// ImageURL draws a picture at the top of the card: an avatar, a cover.
	ImageURL string
	// Alt is what the picture shows, for somebody who cannot see it.
	Alt string
	// Meta is the grey line at the bottom: a count, a joined date.
	Meta string
	// Side is where the card opens: "top", "bottom", "left" or "right". Empty
	// opens downward.
	Side string
}

// ContentID is the id of the card, which the trigger points at.
func (p HoverCardProps) ContentID() string { return p.ID + "-card" }

// Heading is the title inside the card, falling back to the link's own text --
// a card whose heading is missing is a card with no subject.
func (p HoverCardProps) Heading() string {
	if p.Title != "" {
		return p.Title
	}
	return p.Label
}

// PartNames are the parts this component publishes.
func (p HoverCardProps) PartNames() []string {
	return []string{"root", "trigger", "content", "avatar", "title", "subtitle", "description", "meta"}
}

//line components/hover-card.go:77

// HoverCard renders the hover-card component.
func HoverCard(kyse__props HoverCardProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<span\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:67
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("hover-card")))
//line components/hover-card.go:102
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
//line components/hover-card.kyse.go:68
	if kyse__d.Side != "" {
//line components/hover-card.go:109
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-side=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:69
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Side))
//line components/hover-card.go:116
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/hover-card.kyse.go:71
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/hover-card.go:126
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:71", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<a\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"trigger\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:75
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("trigger", "link")))
//line components/hover-card.go:148
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\thref=\"")
	}
	if kyse__err == nil {
		var kyse__v2 string
//line components/hover-card.kyse.go:76
		kyse__v2, kyse__err = kyse__view.TextURL(kyse__d.URL)
//line components/hover-card.go:160
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:76", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-describedby=\"")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:77
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ContentID()))
//line components/hover-card.go:176
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v3 string
//line components/hover-card.kyse.go:78
		kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("trigger"))
//line components/hover-card.go:185
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:78", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:79
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Label)))
//line components/hover-card.go:198
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</a>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<span\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"content\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:87
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("content", "hover-card-content")))
//line components/hover-card.go:218
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:88
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ContentID()))
//line components/hover-card.go:229
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\trole=\"note\"\n")
	}
//line components/hover-card.kyse.go:90
	if kyse__d.Side != "" {
//line components/hover-card.go:239
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-side=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:91
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Side))
//line components/hover-card.go:246
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v4 string
//line components/hover-card.kyse.go:93
		kyse__v4, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("content"))
//line components/hover-card.go:256
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:93", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
//line components/hover-card.kyse.go:95
	if kyse__d.ImageURL != "" {
//line components/hover-card.go:268
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<img\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"avatar\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:98
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("avatar", "hover-card-avatar")))
//line components/hover-card.go:281
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tsrc=\"")
		}
		if kyse__err == nil {
			var kyse__v5 string
//line components/hover-card.kyse.go:99
			kyse__v5, kyse__err = kyse__view.TextURL(kyse__d.ImageURL)
//line components/hover-card.go:293
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:99", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v5)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\talt=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:100
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Alt))
//line components/hover-card.go:309
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v6 string
//line components/hover-card.kyse.go:101
			kyse__v6, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("avatar"))
//line components/hover-card.go:318
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:101", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"title\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:106
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("title", "font-semibold")))
//line components/hover-card.go:341
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v7 string
//line components/hover-card.kyse.go:107
		kyse__v7, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("title"))
//line components/hover-card.go:350
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:107", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v7)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>")
	}
	if kyse__err == nil {
//line components/hover-card.kyse.go:108
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Heading())))
//line components/hover-card.go:363
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
//line components/hover-card.kyse.go:109
	if kyse__d.Subtitle != "" {
//line components/hover-card.go:370
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"subtitle\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:112
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("subtitle", "text-muted-foreground text-sm")))
//line components/hover-card.go:383
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v8 string
//line components/hover-card.kyse.go:113
			kyse__v8, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("subtitle"))
//line components/hover-card.go:392
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:113", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v8)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:114
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Subtitle)))
//line components/hover-card.go:405
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
	}
//line components/hover-card.kyse.go:116
	if kyse__d.Description != "" {
//line components/hover-card.go:413
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"description\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:119
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("description", "text-sm")))
//line components/hover-card.go:426
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v9 string
//line components/hover-card.kyse.go:120
			kyse__v9, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("description"))
//line components/hover-card.go:435
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:120", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v9)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:121
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Description)))
//line components/hover-card.go:448
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
	}
//line components/hover-card.kyse.go:123
	if kyse__d.Meta != "" {
//line components/hover-card.go:456
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"meta\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:126
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("meta", "text-muted-foreground text-xs")))
//line components/hover-card.go:469
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v10 string
//line components/hover-card.kyse.go:127
			kyse__v10, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("meta"))
//line components/hover-card.go:478
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/hover-card.kyse.go:127", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v10)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
		}
		if kyse__err == nil {
//line components/hover-card.kyse.go:128
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Meta)))
//line components/hover-card.go:491
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
