// Code generated by `aru view:build` from kbd.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/kbd.kyse.go:5

// KbdProps is a key, or the keys of a shortcut held together.
//
// It takes the keys and draws what goes between them. That division is the
// whole component: a caller that supplied the separators would be a caller
// writing markup, and the separator is the part that drifts -- a plus here, a
// space there, a hyphen on the page somebody wrote last.
type KbdProps struct {
	// Keys are the keys, in the order they are held down: {"Ctrl", "Shift",
	// "P"}, or {"⌘", "K"}. One key draws no separator, and none draws nothing
	// at all, so a screen can include the shortcut it may not have.
	Keys []string
}

// keyNames are the keys drawn as a symbol, and what each one is called.
//
// A cap reading ⌘ is announced as whatever that character is named in the voice
// speaking, which is rarely "Command" and is sometimes silence. The name goes
// on the element so what is announced is the key.
var keyNames = map[string]string{
	"⌘": "Command",
	"⇧": "Shift",
	"⌥": "Option",
	"⌃": "Control",
	"⏎": "Enter",
	"↩": "Return",
	"⌫": "Backspace",
	"⌦": "Delete",
	"⎋": "Escape",
	"⇥": "Tab",
	"␣": "Space",
	"↑": "Up arrow",
	"↓": "Down arrow",
	"←": "Left arrow",
	"→": "Right arrow",
}

// Name is what assistive technology says for the key at position i, and empty
// for a key written as a word, which already reads as itself.
func (p KbdProps) Name(i int) string {
	if i < 0 || i >= len(p.Keys) {
		return ""
	}
	return keyNames[p.Keys[i]]
}

//line components/kbd.go:63

// Kbd renders the kbd component.
func Kbd(props KbdProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
//line components/kbd.kyse.go:52
	if len(d.Keys) > 0 {
//line components/kbd.go:76
		if err == nil {
			_, err = io.WriteString(w, "\t<span class=\"inline-flex items-center gap-1\">\n")
		}
//line components/kbd.kyse.go:54
		for i := 0; i < len(d.Keys); i++ {
//line components/kbd.go:82
//line components/kbd.kyse.go:55
			if i > 0 {
//line components/kbd.go:85
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t<span>+</span>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<kbd\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\tclass=\"kbd\"\n")
			}
//line components/kbd.kyse.go:60
			if d.Name(i) != "" {
//line components/kbd.go:98
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\taria-label=\"")
				}
				if err == nil {
//line components/kbd.kyse.go:61
					_, err = io.WriteString(w, view.TextAttr(d.Name(i)))
//line components/kbd.go:105
				}
				if err == nil {
					_, err = io.WriteString(w, "\"\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t>")
			}
			if err == nil {
//line components/kbd.kyse.go:63
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Keys[i])))
//line components/kbd.go:117
			}
			if err == nil {
				_, err = io.WriteString(w, "</kbd>\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t</span>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
