// Code generated by `aru view:build` from popover.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/popover.kyse.go:7

// PopoverProps is a button and the panel it shows beside itself.
//
// It is the plain form of the pair: the trigger says what it controls and
// whether the panel is open, and the panel says whether it is hidden. Escape
// closes it and gives focus back to the trigger, a click outside closes it, and
// opening one closes any other -- so two of them on a page cannot both stand
// open over each other.
//
// Where it sits is Side and Align, and both are the stylesheet's: the panel is
// positioned against the trigger by CSS rather than by measuring anything, so
// it lands correctly on the first paint and stays there while the page scrolls.
//
// It is not a dialog. There is no backdrop, nothing behind it is made inert,
// and focus is free to leave -- which is what separates a panel with a filter
// in it from something that has to be answered before the page continues.
type PopoverProps struct {
	// ID is what the trigger and the panel hang their ids off. Two popovers on
	// a page need two.
	ID string
	// Label is the text on the trigger.
	Label string
	// Variant and Size style the trigger. Empty is the default of each.
	Variant string
	Size    string
	// Title is the heading inside the panel. Empty draws no header.
	Title string
	// Description is the sentence under the heading.
	Description string
	// Content is what the panel holds under the header. It is markup, so it
	// comes from another component or from a view.
	Content template.HTML
	// Side is which way the panel opens: "top", "bottom", "left", "right", or
	// the logical "inline-start" and "inline-end", which turn around in a
	// right-to-left document. Empty opens downward.
	Side string
	// Align is where the panel sits along that side: "start", "end" or
	// "center". Empty aligns it to the start.
	Align string
}

// TriggerID is the id of the button that opens the panel.
func (p PopoverProps) TriggerID() string { return p.ID + "-trigger" }

// PanelID is the id of the panel it opens.
func (p PopoverProps) PanelID() string { return p.ID + "-popover" }

//line components/popover.go:64

// Popover renders the popover component.
func Popover(props PopoverProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div class=\"popover\" id=\"")
	}
	if err == nil {
//line components/popover.kyse.go:55
		_, err = io.WriteString(w, view.TextAttr(d.ID))
//line components/popover.go:81
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<button\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\ttype=\"button\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tclass=\"btn\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tid=\"")
	}
	if err == nil {
//line components/popover.kyse.go:59
		_, err = io.WriteString(w, view.TextAttr(d.TriggerID()))
//line components/popover.go:101
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\taria-controls=\"")
	}
	if err == nil {
//line components/popover.kyse.go:60
		_, err = io.WriteString(w, view.TextAttr(d.PanelID()))
//line components/popover.go:112
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\taria-expanded=\"false\"\n")
	}
//line components/popover.kyse.go:62
	if d.Variant != "" {
//line components/popover.go:122
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdata-variant=\"")
		}
		if err == nil {
//line components/popover.kyse.go:63
			_, err = io.WriteString(w, view.TextAttr(d.Variant))
//line components/popover.go:129
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/popover.kyse.go:65
	if d.Size != "" {
//line components/popover.go:137
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdata-size=\"")
		}
		if err == nil {
//line components/popover.kyse.go:66
			_, err = io.WriteString(w, view.TextAttr(d.Size))
//line components/popover.go:144
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>")
	}
	if err == nil {
//line components/popover.kyse.go:68
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Label)))
//line components/popover.go:156
	}
	if err == nil {
		_, err = io.WriteString(w, "</button>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tid=\"")
	}
	if err == nil {
//line components/popover.kyse.go:71
		_, err = io.WriteString(w, view.TextAttr(d.PanelID()))
//line components/popover.go:173
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tdata-popover\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\taria-hidden=\"true\"\n")
	}
//line components/popover.kyse.go:74
	if d.Side != "" {
//line components/popover.go:186
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdata-side=\"")
		}
		if err == nil {
//line components/popover.kyse.go:75
			_, err = io.WriteString(w, view.TextAttr(d.Side))
//line components/popover.go:193
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/popover.kyse.go:77
	if d.Align != "" {
//line components/popover.go:201
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdata-align=\"")
		}
		if err == nil {
//line components/popover.kyse.go:78
			_, err = io.WriteString(w, view.TextAttr(d.Align))
//line components/popover.go:208
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>\n")
	}
//line components/popover.kyse.go:81
	if d.Title != "" {
//line components/popover.go:219
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<header>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t<h3>")
		}
		if err == nil {
//line components/popover.kyse.go:83
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line components/popover.go:229
		}
		if err == nil {
			_, err = io.WriteString(w, "</h3>\n")
		}
//line components/popover.kyse.go:84
		if d.Description != "" {
//line components/popover.go:236
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<p>")
			}
			if err == nil {
//line components/popover.kyse.go:85
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Description)))
//line components/popover.go:243
			}
			if err == nil {
				_, err = io.WriteString(w, "</p>\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t</header>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t")
	}
	if err == nil {
//line components/popover.kyse.go:89
		_, err = io.WriteString(w, view.UnsafeText(d.Content))
//line components/popover.go:259
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
