// Code generated by `aru view:build` from progress.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/progress.kyse.go:5

// ProgressProps is how far along something is, drawn as a bar.
//
// It reports and does not drive: the bar is redrawn when the fragment holding
// it is replaced, and a bar that animated itself would be a bar telling a story
// about work nothing measured.
//
// Two states, and both are the same component. A value that is known fills the
// bar to it and says so with aria-valuenow. A value that is not known fills the
// bar and pulses, and writes no aria-valuenow at all -- which is precisely how
// an unknown share is spelled, and not an omission.
type ProgressProps struct {
	// Label is what is progressing: "Upload", "Import", "Restore". It becomes
	// the accessible name, and a bar without one is announced as a percentage
	// of nothing in particular.
	Label string
	// Value is how far along it is, in the same unit as Max. A value outside
	// the range is held at the nearest end rather than drawn outside the bar.
	Value int
	// Max is the value that means finished. Zero and below mean 100, so Value
	// alone reads as a percentage.
	Max int
	// Indeterminate says the share done is not known -- work has started and
	// nothing counts the steps. It draws a full pulsing bar and no value.
	Indeterminate bool
}

// Ceiling is the value that means finished.
func (p ProgressProps) Ceiling() int {
	if p.Max <= 0 {
		return 100
	}
	return p.Max
}

// Now is Value held inside the bar's own range.
func (p ProgressProps) Now() int {
	if p.Value < 0 {
		return 0
	}
	if ceiling := p.Ceiling(); p.Value > ceiling {
		return ceiling
	}
	return p.Value
}

// Percent is how much of the bar is filled, from 0 to 100.
func (p ProgressProps) Percent() int {
	return p.Now() * 100 / p.Ceiling()
}

// progressWidths are the twenty-one widths the bar is drawn at, one every five
// percent.
//
// They are written out rather than built from the number, because a class name
// assembled at run time never appears in the source the stylesheet is compiled
// from, and the rule for it is never emitted.
var progressWidths = [21]string{
	"w-0", "w-[5%]", "w-[10%]", "w-[15%]", "w-[20%]",
	"w-[25%]", "w-[30%]", "w-[35%]", "w-[40%]", "w-[45%]",
	"w-[50%]", "w-[55%]", "w-[60%]", "w-[65%]", "w-[70%]",
	"w-[75%]", "w-[80%]", "w-[85%]", "w-[90%]", "w-[95%]",
	"w-full",
}

// WidthClass is how far the bar is filled, as the class that draws it.
//
// A class and not a style attribute: the policy this renders under allows no
// inline style, so a width written into one is dropped by the browser and the
// bar never moves. The cost is that it fills in steps of five percent, which is
// one pixel on a bar twenty pixels wide. What is announced is the exact value.
func (p ProgressProps) WidthClass() string {
	return progressWidths[(p.Percent()+2)/5]
}

//line components/progress.go:92

// Progress renders the progress component.
func Progress(props ProgressProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\tclass=\"progress\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\trole=\"progressbar\"\n")
	}
//line components/progress.kyse.go:84
	if d.Label != "" {
//line components/progress.go:114
		if err == nil {
			_, err = io.WriteString(w, "\t\taria-label=\"")
		}
		if err == nil {
//line components/progress.kyse.go:85
			_, err = io.WriteString(w, view.TextAttr(d.Label))
//line components/progress.go:121
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\taria-valuemin=\"0\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\taria-valuemax=\"")
	}
	if err == nil {
//line components/progress.kyse.go:88
		_, err = io.WriteString(w, view.TextAttr(d.Ceiling()))
//line components/progress.go:136
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
//line components/progress.kyse.go:89
	if !d.Indeterminate {
//line components/progress.go:143
		if err == nil {
			_, err = io.WriteString(w, "\t\taria-valuenow=\"")
		}
		if err == nil {
//line components/progress.kyse.go:90
			_, err = io.WriteString(w, view.TextAttr(d.Now()))
//line components/progress.go:150
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, ">\n")
	}
//line components/progress.kyse.go:93
	if d.Indeterminate {
//line components/progress.go:161
		if err == nil {
			_, err = io.WriteString(w, "\t\t<span class=\"w-full animate-pulse\"></span>\n")
		}
	} else {
		if err == nil {
			_, err = io.WriteString(w, "\t\t<span class=\"")
		}
		if err == nil {
//line components/progress.kyse.go:96
			_, err = io.WriteString(w, view.TextAttr(d.WidthClass()))
//line components/progress.go:172
		}
		if err == nil {
			_, err = io.WriteString(w, "\"></span>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
