// Code generated by `aru view:build` from select.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/select.kyse.go:5

// SelectProps is one answer chosen from a list, drawn as the browser's own
// select.
//
// It is the native element and not a button opening a styled list of divs.
// There is one way to choose from a list here, and this is it: the native
// element is the one that submits with the form, that opens as the platform
// picker on a phone, that types-to-find and pages with the keyboard without
// being taught how, and that is still a working control when a script has not
// run. The styled kind buys a menu that matches the rest of the page and pays
// for it with a widget whose state lives in JavaScript -- and the two together
// would be two ways to ask one question.
//
// Field is the labelled row for a box somebody types into; this is the labelled
// row for a list. RadioGroup is the same choice with every option on the screen
// at once, which is worth its space up to about five.
type SelectProps struct {
	// Name is the form field name, and what Page is asked about.
	Name string
	// ID is the id the markup carries, and the id the label points at. Empty
	// uses Name.
	ID string
	// Label is the text above the list.
	Label string
	// Value is the option selected when nothing was rejected: the stored record
	// on an edit form, and empty on a create form. What was chosen on a rejected
	// attempt takes precedence -- see Current.
	Value string
	// Placeholder is the first line, drawn as an option submitting nothing and
	// selected while Value is empty. Empty draws no such line, and the list then
	// starts on its first real option, which is a choice nobody made.
	Placeholder string
	// Hint is the sentence under the list that is always there.
	Hint string
	// Page is the screen's own view.Page, which is what this list asks for its
	// message and for what was chosen. Nil draws no message and keeps Value.
	Page Page
	// Options are the choices, in the order they are drawn.
	Options []SelectOption
	// Required refuses the form while the placeholder is the chosen line.
	Required bool
	// Disabled takes the list out of the form and out of the tab order.
	Disabled bool
}

// SelectOption is one line of the list.
type SelectOption struct {
	// Label is what the line reads.
	Label string
	// Value is what this line submits, and what Value and Current are compared
	// against.
	Value string
	// Disabled draws the line and refuses it, which says a choice exists and is
	// not available -- what removing it from the list cannot say.
	Disabled bool
}

// ElementID is the id the list carries: ID when one was given, and Name when
// none was.
func (p SelectProps) ElementID() string {
	if p.ID != "" {
		return p.ID
	}
	return p.Name
}

// Message is what validation left for this list, or empty.
func (p SelectProps) Message() string {
	if p.Page == nil {
		return ""
	}
	return p.Page.FieldError(p.Name)
}

// Current is the value drawn selected: what was chosen on the rejected attempt,
// and Value when there was none.
func (p SelectProps) Current() string {
	if p.Page == nil {
		return p.Value
	}
	return p.Page.OldOr(p.Name, p.Value)
}

// DescribedBy names the element that explains this list, so the message and the
// hint are announced rather than only shown.
func (p SelectProps) DescribedBy() string {
	if p.Message() != "" {
		return p.ElementID() + "-error"
	}
	if p.Hint != "" {
		return p.ElementID() + "-hint"
	}
	return ""
}

//line components/select.go:112

// Select renders the select component.
func Select(props SelectProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\tclass=\"field\"\n")
	}
//line components/select.kyse.go:103
	if d.Message() != "" {
//line components/select.go:131
		if err == nil {
			_, err = io.WriteString(w, "\t\tdata-invalid=\"true\"\n")
		}
	}
//line components/select.kyse.go:106
	if d.Disabled {
//line components/select.go:138
		if err == nil {
			_, err = io.WriteString(w, "\t\tdata-disabled=\"true\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, ">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<label class=\"label\" for=\"")
	}
	if err == nil {
//line components/select.kyse.go:110
		_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/select.go:152
	}
	if err == nil {
		_, err = io.WriteString(w, "\">")
	}
	if err == nil {
//line components/select.kyse.go:110
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Label)))
//line components/select.go:160
	}
	if err == nil {
		_, err = io.WriteString(w, "</label>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<select\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tclass=\"select\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tid=\"")
	}
	if err == nil {
//line components/select.kyse.go:113
		_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/select.go:177
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tname=\"")
	}
	if err == nil {
//line components/select.kyse.go:114
		_, err = io.WriteString(w, view.TextAttr(d.Name))
//line components/select.go:188
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
//line components/select.kyse.go:115
	if d.DescribedBy() != "" {
//line components/select.go:195
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-describedby=\"")
		}
		if err == nil {
//line components/select.kyse.go:116
			_, err = io.WriteString(w, view.TextAttr(d.DescribedBy()))
//line components/select.go:202
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/select.kyse.go:118
	if d.Message() != "" {
//line components/select.go:210
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-invalid=\"true\"\n")
		}
	}
//line components/select.kyse.go:121
	if d.Required {
//line components/select.go:217
		if err == nil {
			_, err = io.WriteString(w, "\t\t\trequired\n")
		}
	}
//line components/select.kyse.go:124
	if d.Disabled {
//line components/select.go:224
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdisabled\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>\n")
	}
//line components/select.kyse.go:128
	if d.Placeholder != "" {
//line components/select.go:234
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<option\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\tvalue=\"\"\n")
		}
//line components/select.kyse.go:131
		if d.Current() == "" {
//line components/select.go:243
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\tselected\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t>")
		}
		if err == nil {
//line components/select.kyse.go:134
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Placeholder)))
//line components/select.go:254
		}
		if err == nil {
			_, err = io.WriteString(w, "</option>\n")
		}
	}
//line components/select.kyse.go:136
	for _, option := range d.Options {
		_ = option
//line components/select.go:263
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<option\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\tvalue=\"")
		}
		if err == nil {
//line components/select.kyse.go:138
			_, err = io.WriteString(w, view.TextAttr(option.Value))
//line components/select.go:273
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
//line components/select.kyse.go:139
		if option.Value == d.Current() {
//line components/select.go:280
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\tselected\n")
			}
		}
//line components/select.kyse.go:142
		if option.Disabled {
//line components/select.go:287
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\tdisabled\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t>")
		}
		if err == nil {
//line components/select.kyse.go:145
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(option.Label)))
//line components/select.go:298
		}
		if err == nil {
			_, err = io.WriteString(w, "</option>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</select>\n")
	}
//line components/select.kyse.go:148
	if d.Message() != "" {
//line components/select.go:309
		if err == nil {
			_, err = io.WriteString(w, "\t\t<p id=\"")
		}
		if err == nil {
//line components/select.kyse.go:149
			_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/select.go:316
		}
		if err == nil {
			_, err = io.WriteString(w, "-error\" class=\"text-destructive text-sm\">")
		}
		if err == nil {
//line components/select.kyse.go:149
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Message())))
//line components/select.go:324
		}
		if err == nil {
			_, err = io.WriteString(w, "</p>\n")
		}
	}
//line components/select.kyse.go:151
	if d.Message() == "" {
//line components/select.go:332
//line components/select.kyse.go:152
		if d.Hint != "" {
//line components/select.go:335
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<p id=\"")
			}
			if err == nil {
//line components/select.kyse.go:153
				_, err = io.WriteString(w, view.TextAttr(d.ElementID()))
//line components/select.go:342
			}
			if err == nil {
				_, err = io.WriteString(w, "-hint\" class=\"text-muted-foreground text-sm\">")
			}
			if err == nil {
//line components/select.kyse.go:153
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Hint)))
//line components/select.go:350
			}
			if err == nil {
				_, err = io.WriteString(w, "</p>\n")
			}
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
