// Code generated by `aru view:build` from sidebar.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
	"html/template"
)

//line components/sidebar.kyse.go:7

// SidebarProps is the column of navigation beside a page: groups of links, with
// the one being looked at marked.
//
// It is an aside holding one nav, and the page content is its next sibling.
// That order is not a suggestion -- the stylesheet gives the element after the
// aside the margin that leaves room for the column, so a wrapper between them
// leaves the page underneath the sidebar.
//
// The current entry carries aria-current, which is both what the stylesheet
// paints and what a screen reader announces. Marking it with a class instead
// gives the second half to nobody.
//
// # What collapsing it costs
//
// Collapsed is the state the page is served in. Closing and reopening it after
// that belongs to the button that does it, and the button cannot live here: the
// sidebar is inert while it is closed, so a control inside it is unreachable
// exactly when it is needed. ID is the handle that button uses.
//
// On a narrow screen the column becomes an overlay, and it closes itself when a
// link inside it is followed or the shade beside it is clicked -- so a page
// that never draws a button of its own is still usable there.
type SidebarProps struct {
	// ID is the handle the control that opens and closes the sidebar reaches it
	// by.
	ID string
	// Groups are the sections of the navigation, top to bottom.
	Groups []SidebarGroup
	// Label names the navigation landmark, which is what a screen reader offers
	// when it lists the ways around a page. Empty means "Sidebar".
	Label string
	// Side is "left" or "right". Empty means left, and it is physical: it names
	// a side of the viewport rather than the start of a line, so it does not
	// turn around in a right-to-left document.
	Side string
	// Header and Footer are the regions above and below the scrolling list --
	// a workspace switcher, an account control. Empty draws neither.
	Header template.HTML
	Footer template.HTML
	// Collapsed serves the page with the column already folded away.
	Collapsed bool
	// MobileOpen serves a narrow screen with the overlay already open. It is
	// separate from Collapsed because the two are different screens: the column
	// is furniture on a wide one and a modal on a narrow one.
	MobileOpen bool
}

// SidebarGroup is one titled run of entries.
type SidebarGroup struct {
	// Label is the heading over the group. Empty draws the entries with no
	// heading and leaves the group unnamed rather than naming it nothing.
	Label string
	// Items are the entries, top to bottom.
	Items []SidebarItem
}

// SidebarItem is one entry: somewhere to go, and whether that is where we are.
//
// It is a link. An entry that acts rather than navigates belongs in Header or
// Footer, where a button is what it looks like -- a list of links with one
// button in it reads as a link that behaves strangely.
type SidebarItem struct {
	// Label is the text.
	Label string
	// URL is where it goes.
	URL string
	// Current marks this as the page being looked at. At most one per sidebar,
	// because the question it answers has one answer.
	Current bool
	// Disabled draws the entry unavailable and says so.
	Disabled bool
}

// Landmark is what the navigation is announced as.
func (p SidebarProps) Landmark() string {
	if p.Label == "" {
		return "Sidebar"
	}
	return p.Label
}

// Edge is the side of the viewport the column is fixed to.
func (p SidebarProps) Edge() string {
	if p.Side == "" {
		return "left"
	}
	return p.Side
}

//line components/sidebar.go:109

// Sidebar renders the sidebar component.
func Sidebar(kyse__props SidebarProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<aside\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"sidebar\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tid=\"")
	}
	if kyse__err == nil {
//line components/sidebar.kyse.go:100
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/sidebar.go:134
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-side=\"")
	}
	if kyse__err == nil {
//line components/sidebar.kyse.go:101
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Edge()))
//line components/sidebar.go:145
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
//line components/sidebar.kyse.go:102
	if kyse__d.Collapsed {
//line components/sidebar.go:152
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-initial-open=\"false\"\n")
		}
	}
//line components/sidebar.kyse.go:105
	if kyse__d.MobileOpen {
//line components/sidebar.go:159
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-initial-mobile-open=\"true\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<nav aria-label=\"")
	}
	if kyse__err == nil {
//line components/sidebar.kyse.go:109
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Landmark()))
//line components/sidebar.go:173
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
//line components/sidebar.kyse.go:110
	if kyse__d.Header != "" {
//line components/sidebar.go:180
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<header>")
		}
		if kyse__err == nil {
//line components/sidebar.kyse.go:111
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(kyse__d.Header))
//line components/sidebar.go:187
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</header>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<section>\n")
	}
//line components/sidebar.kyse.go:115
	for _, group := range kyse__d.Groups {
		_ = group
//line components/sidebar.go:202
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<div\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\trole=\"group\"\n")
		}
//line components/sidebar.kyse.go:118
		if group.Label != "" {
//line components/sidebar.go:211
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\taria-label=\"")
			}
			if kyse__err == nil {
//line components/sidebar.kyse.go:119
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(group.Label))
//line components/sidebar.go:218
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>\n")
		}
//line components/sidebar.kyse.go:122
		if group.Label != "" {
//line components/sidebar.go:229
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t<h3>")
			}
			if kyse__err == nil {
//line components/sidebar.kyse.go:123
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(group.Label)))
//line components/sidebar.go:236
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</h3>\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<ul>\n")
		}
//line components/sidebar.kyse.go:126
		for _, item := range group.Items {
			_ = item
//line components/sidebar.go:248
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t<li>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\t<a\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\t\thref=\"")
			}
			if kyse__err == nil {
				var kyse__v1 string
//line components/sidebar.kyse.go:129
				kyse__v1, kyse__err = kyse__view.TextURL(item.URL)
//line components/sidebar.go:262
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/sidebar.kyse.go:129", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
//line components/sidebar.kyse.go:130
			if item.Current {
//line components/sidebar.go:274
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\t\t\taria-current=\"page\"\n")
				}
			}
//line components/sidebar.kyse.go:133
			if item.Disabled {
//line components/sidebar.go:281
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\t\t\taria-disabled=\"true\"\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t\t><span>")
			}
			if kyse__err == nil {
//line components/sidebar.kyse.go:136
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(item.Label)))
//line components/sidebar.go:292
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</span></a>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\t\t</li>\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t</ul>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t</div>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</section>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
//line components/sidebar.kyse.go:144
	if kyse__d.Footer != "" {
//line components/sidebar.go:316
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<footer>")
		}
		if kyse__err == nil {
//line components/sidebar.kyse.go:145
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(kyse__d.Footer))
//line components/sidebar.go:323
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</footer>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</nav>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</aside>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
