// Code generated by `aru view:build` from switch.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line components/switch.kyse.go:5

// SwitchProps is one setting that is on or off, drawn as a track with a thumb
// and named from the left.
//
// It is the same element as Checkbox with role="switch" on it, and it is a
// separate component rather than a flag on that one because the two are read
// aloud differently -- "on" and "off" against "ticked" and "not ticked" -- and
// because they are used at different moments. A checkbox is an answer given
// while filling a form in. A switch is a setting somebody throws, and the row
// reads as a setting: the name on the left, the control on the right, the way
// the rest of the row does.
//
// Field draws neither. Its row is a name over a box somebody types into.
//
// aria-checked is deliberately not written. The state belongs to the input, and
// the browser reports it from there; an attribute written once at render would
// still say "off" after somebody turned the switch on, which is worse than
// having said nothing.
type SwitchProps struct {
	// ComponentProps is the class, attributes and parts the caller adds.
	ComponentProps
	// Name is the form field name, and what Page is asked about.
	Name string
	// ID is the id the markup carries, and the id the label points at. Empty
	// uses Name -- which a list of switches sharing one name has to set, since
	// otherwise every label in the list points at the first switch.
	ID string
	// Label is the text naming the setting.
	Label string
	// Value is what a switch that is on submits. Empty submits "on", which is
	// what a browser sends for a checkbox with no value of its own.
	Value string
	// Hint is the sentence under the label saying what the setting does.
	Hint string
	// Page is the screen's own view.Page, which is what this switch asks for its
	// message and for whether it came back on. Nil draws no message and keeps
	// On.
	Page Page
	// On is whether the switch starts on when nothing was rejected: the stored
	// record on an edit form, and the default on a new one.
	On bool
	// Disabled takes the switch out of the form and out of the tab order.
	Disabled bool
}

// ElementID is the id the switch carries: ID when one was given, and Name when
// none was.
func (p SwitchProps) ElementID() string {
	if p.ID != "" {
		return p.ID
	}
	return p.Name
}

// SubmittedValue is what a switch that is on sends: Value when it was given, and
// "on" when it was not.
func (p SwitchProps) SubmittedValue() string {
	if p.Value == "" {
		return "on"
	}
	return p.Value
}

// Message is what validation left for this switch, or empty.
func (p SwitchProps) Message() string {
	if p.Page == nil {
		return ""
	}
	return p.Page.FieldError(p.Name)
}

// Current reports whether the switch is drawn on.
//
// A switch that is on submits its value and one that is off submits nothing at
// all, so what comes back from a rejected attempt answers only half the
// question: the value being there means it was on, and it being absent means
// either that it was off or that there was no attempt. Absent therefore falls
// back to On, which is right on the form nobody submitted and wrong in one case
// -- a switch somebody turned off on an attempt that was then rejected comes
// back on. Telling the two apart needs a second field on the wire, and this
// component does not invent one.
func (p SwitchProps) Current() bool {
	if p.Page == nil {
		return p.On
	}
	fallback := ""
	if p.On {
		fallback = p.SubmittedValue()
	}
	return p.Page.OldOr(p.Name, fallback) == p.SubmittedValue()
}

// DescribedBy names the element that explains this switch, so the message and
// the hint are announced rather than only shown.
func (p SwitchProps) DescribedBy() string {
	if p.Message() != "" {
		return p.ElementID() + "-error"
	}
	if p.Hint != "" {
		return p.ElementID() + "-hint"
	}
	return ""
}

// PartNames are the parts this component publishes.
func (p SwitchProps) PartNames() []string {
	return []string{"root", "content", "label", "input", "message", "hint"}
}

//line components/switch.go:127

// Switch renders the switch component.
func Switch(kyse__props SwitchProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-part=\"root\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tclass=\"")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:114
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.RootClass("field")))
//line components/switch.go:152
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\tdata-orientation=\"horizontal\"\n")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line components/switch.kyse.go:116
		kyse__v1, kyse__err = kyse__view.Attributes(kyse__d.RootAttrs())
//line components/switch.go:164
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/switch.kyse.go:116", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
//line components/switch.kyse.go:117
	if kyse__d.Message() != "" {
//line components/switch.go:173
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-invalid=\"true\"\n")
		}
	}
//line components/switch.kyse.go:120
	if kyse__d.Disabled {
//line components/switch.go:180
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-disabled=\"true\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, ">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<section\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"content\"\n")
	}
//line components/switch.kyse.go:126
	if kyse__d.PartClass("content") != "" {
//line components/switch.go:196
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/switch.kyse.go:127
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("content")))
//line components/switch.go:203
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		var kyse__v2 string
//line components/switch.kyse.go:129
		kyse__v2, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("content"))
//line components/switch.go:213
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/switch.kyse.go:129", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<label\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-part=\"label\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:133
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("label", "label")))
//line components/switch.go:235
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tfor=\"")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:134
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ElementID()))
//line components/switch.go:246
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v3 string
//line components/switch.kyse.go:135
		kyse__v3, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("label"))
//line components/switch.go:255
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/switch.kyse.go:135", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:136
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Label)))
//line components/switch.go:268
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</label>\n")
	}
//line components/switch.kyse.go:137
	if kyse__d.Message() != "" {
//line components/switch.go:275
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<p\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tdata-part=\"message\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/switch.kyse.go:140
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ElementID()))
//line components/switch.go:288
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "-error\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"")
		}
		if kyse__err == nil {
//line components/switch.kyse.go:141
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("message", "text-destructive text-sm")))
//line components/switch.go:299
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			var kyse__v4 string
//line components/switch.kyse.go:142
			kyse__v4, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("message"))
//line components/switch.go:308
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "components/switch.kyse.go:142", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
		}
		if kyse__err == nil {
//line components/switch.kyse.go:143
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Message())))
//line components/switch.go:321
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
//line components/switch.kyse.go:145
	if kyse__d.Message() == "" {
//line components/switch.go:329
//line components/switch.kyse.go:146
		if kyse__d.Hint != "" {
//line components/switch.go:332
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<p\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tdata-part=\"hint\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tid=\"")
			}
			if kyse__err == nil {
//line components/switch.kyse.go:149
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ElementID()))
//line components/switch.go:345
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "-hint\"\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"")
			}
			if kyse__err == nil {
//line components/switch.kyse.go:150
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("hint", "text-muted-foreground text-sm")))
//line components/switch.go:356
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
			if kyse__err == nil {
				var kyse__v5 string
//line components/switch.kyse.go:151
				kyse__v5, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("hint"))
//line components/switch.go:365
				if kyse__err != nil {
					kyse__err = kyse__fmt.Errorf("%s: %w", "components/switch.kyse.go:151", kyse__err)
				} else {
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v5)
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>")
			}
			if kyse__err == nil {
//line components/switch.kyse.go:152
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Hint)))
//line components/switch.go:378
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
			}
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</section>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<input\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tdata-part=\"input\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tclass=\"")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:158
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PartClass("input", "input")))
//line components/switch.go:400
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\ttype=\"checkbox\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\trole=\"switch\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tid=\"")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:161
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ElementID()))
//line components/switch.go:417
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\tname=\"")
	}
	if kyse__err == nil {
//line components/switch.kyse.go:162
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Name))
//line components/switch.go:428
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		var kyse__v6 string
//line components/switch.kyse.go:163
		kyse__v6, kyse__err = kyse__view.Attributes(kyse__d.PartAttrs("input"))
//line components/switch.go:437
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "components/switch.kyse.go:163", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
		}
	}
//line components/switch.kyse.go:164
	if kyse__d.Value != "" {
//line components/switch.go:446
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tvalue=\"")
		}
		if kyse__err == nil {
//line components/switch.kyse.go:165
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Value))
//line components/switch.go:453
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/switch.kyse.go:167
	if kyse__d.Current() {
//line components/switch.go:461
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tchecked\n")
		}
	}
//line components/switch.kyse.go:170
	if kyse__d.DescribedBy() != "" {
//line components/switch.go:468
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-describedby=\"")
		}
		if kyse__err == nil {
//line components/switch.kyse.go:171
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.DescribedBy()))
//line components/switch.go:475
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/switch.kyse.go:173
	if kyse__d.Message() != "" {
//line components/switch.go:483
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-invalid=\"true\"\n")
		}
	}
//line components/switch.kyse.go:176
	if kyse__d.Disabled {
//line components/switch.go:490
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdisabled\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__strings.Builder{}
)
