// Code generated by `aru view:build` from table.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/table.kyse.go:5

// TableProps is a grid of rows under a row of headers.
//
// The head and the body are drawn from two slices that line up by position and
// by nothing else: the third cell of every row is the third column, whatever
// that column is called. A row carrying more cells than the table has columns
// draws them anyway, under no header, which is visible on the screen and
// therefore fixable.
//
// # What it does not do
//
// It does not sort, page or filter. Each of those is a request the server
// answers, and a component that made them would be a component deciding what a
// caller may ask for; the table draws the rows it was handed.
//
// It does not format. A number arrives as the string it should read as, because
// a thousands separator and a currency are decided where the locale is known,
// and a component that chose would choose wrong in half the places it is drawn.
type TableProps struct {
	// Caption is the sentence saying what the table lists. It is drawn under
	// the table and is the table's name to assistive technology, which is what
	// makes a page of three tables navigable. Empty draws none.
	Caption string
	// Columns are the headers, left to right. Each one also decides where the
	// cells beneath it sit.
	Columns []TableColumn
	// Rows are the lines. Empty draws Empty rather than a head with nothing
	// under it.
	Rows []TableRow
	// Empty is what stands in when there are no rows. A table with headers and
	// no body reads as one that failed to load rather than one with nothing to
	// list.
	Empty EmptyProps
}

// TableColumn is one header, and where everything under it sits.
type TableColumn struct {
	// Label is the header text.
	Label string
	// Align is "start", "center" or "end". Empty means "start".
	//
	// A column of numbers is "end": the digits then line up on the units, which
	// is what makes two amounts comparable by looking at them.
	Align string
}

// AlignClass is the alignment this column draws with.
func (c TableColumn) AlignClass() string {
	switch c.Align {
	case "center":
		return "text-center"
	case "end":
		return "text-end"
	default:
		return "text-start"
	}
}

// TableRow is one line of the body.
type TableRow struct {
	// Cells are the values, in the order Columns names them.
	Cells []TableCell
}

// TableCell is one value, as text or as markup.
type TableCell struct {
	// Text is what the cell says. It is escaped on the way out, and it is what
	// almost every cell is.
	Text string
	// HTML is markup, drawn in place of Text whenever it is set.
	//
	// Nothing here escapes it, so what goes in is what the page gets, and the
	// caller is what makes that safe: pass what another component returned --
	// a badge, a button, an icon -- and never a string assembled around a value
	// somebody typed.
	HTML template.HTML
}

// AlignClass is the alignment of the column at position i, and the default
// where a row carries more cells than the table has columns.
func (p TableProps) AlignClass(i int) string {
	if i < len(p.Columns) {
		return p.Columns[i].AlignClass()
	}
	return TableColumn{}.AlignClass()
}

//line components/table.go:104

// Table renders the table component.
func Table(props TableProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
//line components/table.kyse.go:93
	if len(d.Rows) > 0 {
//line components/table.go:117
		if err == nil {
			_, err = io.WriteString(w, "\t<div class=\"table-container\">\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t<table class=\"table\">\n")
		}
//line components/table.kyse.go:96
		if d.Caption != "" {
//line components/table.go:126
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t<caption>")
			}
			if err == nil {
//line components/table.kyse.go:97
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Caption)))
//line components/table.go:133
			}
			if err == nil {
				_, err = io.WriteString(w, "</caption>\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<thead>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t<tr>\n")
		}
//line components/table.kyse.go:101
		for _, column := range d.Columns {
			_ = column
//line components/table.go:148
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t\t<th scope=\"col\" class=\"")
			}
			if err == nil {
//line components/table.kyse.go:102
				_, err = io.WriteString(w, view.TextAttr(column.AlignClass()))
//line components/table.go:155
			}
			if err == nil {
				_, err = io.WriteString(w, "\">")
			}
			if err == nil {
//line components/table.kyse.go:102
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(column.Label)))
//line components/table.go:163
			}
			if err == nil {
				_, err = io.WriteString(w, "</th>\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t</tr>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t</thead>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<tbody>\n")
		}
//line components/table.kyse.go:107
		for _, row := range d.Rows {
			_ = row
//line components/table.go:181
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t<tr>\n")
			}
//line components/table.kyse.go:109
			for i := 0; i < len(row.Cells); i++ {
//line components/table.go:187
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t\t<td class=\"")
				}
				if err == nil {
//line components/table.kyse.go:110
					_, err = io.WriteString(w, view.TextAttr(d.AlignClass(i)))
//line components/table.go:194
				}
				if err == nil {
					_, err = io.WriteString(w, "\">\n")
				}
//line components/table.kyse.go:111
				if row.Cells[i].HTML != "" {
//line components/table.go:201
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t\t")
					}
					if err == nil {
//line components/table.kyse.go:112
						_, err = io.WriteString(w, view.UnsafeText(row.Cells[i].HTML))
//line components/table.go:208
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
				} else {
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t\t\t\t\t")
					}
					if err == nil {
//line components/table.kyse.go:114
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(row.Cells[i].Text)))
//line components/table.go:220
					}
					if err == nil {
						_, err = io.WriteString(w, "\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t\t\t\t\t</td>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t</tr>\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t</tbody>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t</table>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t</div>\n")
		}
	} else {
		if err == nil {
			_, err = io.WriteString(w, "\t")
		}
		if err == nil {
//line components/table.kyse.go:124
			_, err = io.WriteString(w, view.UnsafeText(Empty(d.Empty)))
//line components/table.go:250
		}
		if err == nil {
			_, err = io.WriteString(w, "\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
