// Code generated by `aru view:build` from tabs.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/tabs.kyse.go:7

// TabsProps is one region of a page with several views of itself and a row of
// buttons that choose between them.
//
// The row is a tablist, each button is a tab that names the panel it controls,
// and each panel names the tab that labels it. That pair of references is what
// the keyboard and the screen reader both run on: the arrow keys move along the
// row, Home and End reach its ends, and only the selected tab is in the tab
// order, so one press of Tab leaves the row rather than walking through every
// button in it.
//
// Every panel is rendered, and the ones not being shown carry the hidden
// attribute. That is what makes the first paint correct before any script has
// run, and it is why a panel is a value rather than an address: switching tabs
// is not a request.
type TabsProps struct {
	// ID is what every tab and panel hangs its id off. Two tab sets on one page
	// need two, or the second set's panels answer to the first set's tabs.
	ID string
	// Tabs are the buttons and their panels, in the order they are drawn.
	Tabs []Tab
	// Active is the ID of the tab drawn selected. Empty selects the first one
	// that is not disabled.
	Active string
	// Label names the row for a screen reader, which announces it as a set
	// rather than as loose buttons.
	Label string
	// Variant is "line" for the underlined row. Empty is the default.
	Variant string
	// Vertical stacks the row down the side instead of across the top. It also
	// moves the arrow keys from left and right to up and down, which is why it
	// is a property of the set and not a class the caller adds.
	Vertical bool
}

// Tab is one button and the panel it shows.
type Tab struct {
	// ID identifies the tab within the set. It is part of two element ids, so
	// it has to be unique among the tabs, and nobody sees it.
	ID string
	// Label is the text on the button.
	Label string
	// Panel is what the tab shows. It is markup, so it comes from another
	// component or from a view.
	Panel template.HTML
	// Disabled draws the tab unusable and takes it out of the arrow-key order.
	Disabled bool
}

// TabID is the id of a tab's button.
func (p TabsProps) TabID(t Tab) string { return p.ID + "-tab-" + t.ID }

// PanelID is the id of the panel a tab controls.
func (p TabsProps) PanelID(t Tab) string { return p.ID + "-panel-" + t.ID }

// IsActive reports whether a tab is the one being shown.
//
// With no Active named it is the first tab that is not disabled, rather than
// the first tab: a set whose first entry is unavailable would otherwise open
// showing a panel nothing can select again.
func (p TabsProps) IsActive(t Tab) bool {
	if p.Active != "" {
		return t.ID == p.Active
	}
	for _, candidate := range p.Tabs {
		if candidate.Disabled {
			continue
		}
		return candidate.ID == t.ID
	}
	return false
}

// Selected is the aria-selected value of a tab.
func (p TabsProps) Selected(t Tab) string {
	if p.IsActive(t) {
		return "true"
	}
	return "false"
}

// TabIndex is a tab's place in the keyboard order.
//
// The selected tab is the single entry point into the row and the arrow keys
// reach the rest, which is what keeps a set of nine tabs from being nine stops
// on the way to the panel.
func (p TabsProps) TabIndex(t Tab) string {
	if p.IsActive(t) {
		return "0"
	}
	return "-1"
}

// Folded reports whether a panel starts hidden.
func (p TabsProps) Folded(t Tab) bool { return !p.IsActive(t) }

// Orientation is which way the row runs, which is also what decides the pair of
// arrow keys that moves along it.
func (p TabsProps) Orientation() string {
	if p.Vertical {
		return "vertical"
	}
	return "horizontal"
}

//line components/tabs.go:122

// Tabs renders the tabs component.
func Tabs(props TabsProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div class=\"tabs\" id=\"")
	}
	if err == nil {
//line components/tabs.kyse.go:113
		_, err = io.WriteString(w, view.TextAttr(d.ID))
//line components/tabs.go:139
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\trole=\"tablist\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\taria-orientation=\"")
	}
	if err == nil {
//line components/tabs.kyse.go:116
		_, err = io.WriteString(w, view.TextAttr(d.Orientation()))
//line components/tabs.go:156
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
//line components/tabs.kyse.go:117
	if d.Label != "" {
//line components/tabs.go:163
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-label=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:118
			_, err = io.WriteString(w, view.TextAttr(d.Label))
//line components/tabs.go:170
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/tabs.kyse.go:120
	if d.Variant != "" {
//line components/tabs.go:178
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tdata-variant=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:121
			_, err = io.WriteString(w, view.TextAttr(d.Variant))
//line components/tabs.go:185
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>\n")
	}
//line components/tabs.kyse.go:124
	for _, tab := range d.Tabs {
		_ = tab
//line components/tabs.go:197
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t<button\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\ttype=\"button\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\trole=\"tab\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\tid=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:128
			_, err = io.WriteString(w, view.TextAttr(d.TabID(tab)))
//line components/tabs.go:213
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\taria-controls=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:129
			_, err = io.WriteString(w, view.TextAttr(d.PanelID(tab)))
//line components/tabs.go:224
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\taria-selected=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:130
			_, err = io.WriteString(w, view.TextAttr(d.Selected(tab)))
//line components/tabs.go:235
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\ttabindex=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:131
			_, err = io.WriteString(w, view.TextAttr(d.TabIndex(tab)))
//line components/tabs.go:246
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
//line components/tabs.kyse.go:132
		if tab.Disabled {
//line components/tabs.go:253
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\taria-disabled=\"true\"\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t>")
		}
		if err == nil {
//line components/tabs.kyse.go:135
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(tab.Label)))
//line components/tabs.go:264
		}
		if err == nil {
			_, err = io.WriteString(w, "</button>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
//line components/tabs.kyse.go:139
	for _, tab := range d.Tabs {
		_ = tab
//line components/tabs.go:279
		if err == nil {
			_, err = io.WriteString(w, "\t\t<div\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\trole=\"tabpanel\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tid=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:142
			_, err = io.WriteString(w, view.TextAttr(d.PanelID(tab)))
//line components/tabs.go:292
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-labelledby=\"")
		}
		if err == nil {
//line components/tabs.kyse.go:143
			_, err = io.WriteString(w, view.TextAttr(d.TabID(tab)))
//line components/tabs.go:303
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\ttabindex=\"0\"\n")
		}
//line components/tabs.kyse.go:145
		if d.Folded(tab) {
//line components/tabs.go:313
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\thidden\n")
			}
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t>")
		}
		if err == nil {
//line components/tabs.kyse.go:148
			_, err = io.WriteString(w, view.UnsafeText(tab.Panel))
//line components/tabs.go:324
		}
		if err == nil {
			_, err = io.WriteString(w, "</div>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
	_ = strings.Builder{}
)
