// Code generated by `aru view:build` from tabs.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	kyse__template "html/template"
	kyse__io "io"
	kyse__strings "strings"

	kyse__view "github.com/arandu-io/framework/view"
	"html/template"
)

//line components/tabs.kyse.go:7

// TabsProps is one region of a page with several views of itself and a row of
// buttons that choose between them.
//
// The row is a tablist, each button is a tab that names the panel it controls,
// and each panel names the tab that labels it. That pair of references is what
// the keyboard and the screen reader both run on: the arrow keys move along the
// row, Home and End reach its ends, and only the selected tab is in the tab
// order, so one press of Tab leaves the row rather than walking through every
// button in it.
//
// Every panel is rendered, and the ones not being shown carry the hidden
// attribute. That is what makes the first paint correct before any script has
// run, and it is why a panel is a value rather than an address: switching tabs
// is not a request.
type TabsProps struct {
	// ID is what every tab and panel hangs its id off. Two tab sets on one page
	// need two, or the second set's panels answer to the first set's tabs.
	ID string
	// Tabs are the buttons and their panels, in the order they are drawn.
	Tabs []Tab
	// Active is the ID of the tab drawn selected. Empty selects the first one
	// that is not disabled.
	Active string
	// Label names the row for a screen reader, which announces it as a set
	// rather than as loose buttons.
	Label string
	// Variant is "line" for the underlined row. Empty is the default.
	Variant string
	// Vertical stacks the row down the side instead of across the top. It also
	// moves the arrow keys from left and right to up and down, which is why it
	// is a property of the set and not a class the caller adds.
	Vertical bool
}

// Tab is one button and the panel it shows.
type Tab struct {
	// ID identifies the tab within the set. It is part of two element ids, so
	// it has to be unique among the tabs, and nobody sees it.
	ID string
	// Label is the text on the button.
	Label string
	// Panel is what the tab shows. It is markup, so it comes from another
	// component or from a view.
	Panel template.HTML
	// Disabled draws the tab unusable and takes it out of the arrow-key order.
	Disabled bool
}

// TabID is the id of a tab's button.
func (p TabsProps) TabID(t Tab) string { return p.ID + "-tab-" + t.ID }

// PanelID is the id of the panel a tab controls.
func (p TabsProps) PanelID(t Tab) string { return p.ID + "-panel-" + t.ID }

// IsActive reports whether a tab is the one being shown.
//
// With no Active named it is the first tab that is not disabled, rather than
// the first tab: a set whose first entry is unavailable would otherwise open
// showing a panel nothing can select again.
func (p TabsProps) IsActive(t Tab) bool {
	if p.Active != "" {
		return t.ID == p.Active
	}
	for _, candidate := range p.Tabs {
		if candidate.Disabled {
			continue
		}
		return candidate.ID == t.ID
	}
	return false
}

// Selected is the aria-selected value of a tab.
func (p TabsProps) Selected(t Tab) string {
	if p.IsActive(t) {
		return "true"
	}
	return "false"
}

// TabIndex is a tab's place in the keyboard order.
//
// The selected tab is the single entry point into the row and the arrow keys
// reach the rest, which is what keeps a set of nine tabs from being nine stops
// on the way to the panel.
func (p TabsProps) TabIndex(t Tab) string {
	if p.IsActive(t) {
		return "0"
	}
	return "-1"
}

// Folded reports whether a panel starts hidden.
func (p TabsProps) Folded(t Tab) bool { return !p.IsActive(t) }

// Orientation is which way the row runs, which is also what decides the pair of
// arrow keys that moves along it.
func (p TabsProps) Orientation() string {
	if p.Vertical {
		return "vertical"
	}
	return "horizontal"
}

//line components/tabs.go:123

// Tabs renders the tabs component.
func Tabs(kyse__props TabsProps) kyse__template.HTML {
	kyse__d := kyse__props
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__w := &kyse__strings.Builder{}
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div class=\"tabs\" id=\"")
	}
	if kyse__err == nil {
//line components/tabs.kyse.go:113
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.ID))
//line components/tabs.go:142
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\trole=\"tablist\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\taria-orientation=\"")
	}
	if kyse__err == nil {
//line components/tabs.kyse.go:116
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Orientation()))
//line components/tabs.go:159
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
//line components/tabs.kyse.go:117
	if kyse__d.Label != "" {
//line components/tabs.go:166
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-label=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:118
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Label))
//line components/tabs.go:173
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
//line components/tabs.kyse.go:120
	if kyse__d.Variant != "" {
//line components/tabs.go:181
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tdata-variant=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:121
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Variant))
//line components/tabs.go:188
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t>\n")
	}
//line components/tabs.kyse.go:124
	for _, tab := range kyse__d.Tabs {
		_ = tab
//line components/tabs.go:200
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<button\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\ttype=\"button\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\trole=\"tab\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:128
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.TabID(tab)))
//line components/tabs.go:216
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\taria-controls=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:129
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PanelID(tab)))
//line components/tabs.go:227
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\taria-selected=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:130
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Selected(tab)))
//line components/tabs.go:238
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\ttabindex=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:131
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.TabIndex(tab)))
//line components/tabs.go:249
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
//line components/tabs.kyse.go:132
		if tab.Disabled {
//line components/tabs.go:256
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\taria-disabled=\"true\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:135
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(tab.Label)))
//line components/tabs.go:267
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</button>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
//line components/tabs.kyse.go:139
	for _, tab := range kyse__d.Tabs {
		_ = tab
//line components/tabs.go:282
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<div\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\trole=\"tabpanel\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tid=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:142
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.PanelID(tab)))
//line components/tabs.go:295
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\taria-labelledby=\"")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:143
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.TabID(tab)))
//line components/tabs.go:306
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\ttabindex=\"0\"\n")
		}
//line components/tabs.kyse.go:145
		if kyse__d.Folded(tab) {
//line components/tabs.go:316
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thidden\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t>")
		}
		if kyse__err == nil {
//line components/tabs.kyse.go:148
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.UnsafeText(tab.Panel))
//line components/tabs.go:327
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	_ = kyse__err
	return kyse__template.HTML(kyse__w.String())
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__view.UnsafeText
	_ = kyse__strings.Builder{}
)
