// Code generated by `aru view:build` from textarea.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package components

import (
	"html/template"
	"io"
	"strings"

	"github.com/arandu-io/framework/view"
)

//line components/textarea.kyse.go:5

// TextareaProps is a labelled textarea, with its error.
//
// It is FieldProps without the type and with rows, kept separate because a
// textarea is a different element with a different way of carrying its value --
// between the tags rather than in an attribute -- and one component branching on
// which element to draw would be two components sharing a name.
type TextareaProps struct {
	// Name is the form field name, and the id the label points at.
	Name string
	// Label is the text above the box.
	Label string
	// Value is what the box starts with.
	Value string
	// Placeholder is the grey text inside an empty box.
	Placeholder string
	// Hint is the sentence under the box.
	Hint string
	// Error is what came back from validation.
	Error string
	// Rows is the height in lines. Zero draws the browser default.
	Rows int
	// Required marks the box required.
	Required bool
}

// DescribedBy names the element that explains this box.
func (p TextareaProps) DescribedBy() string {
	if p.Error != "" {
		return p.Name + "-error"
	}
	if p.Hint != "" {
		return p.Name + "-hint"
	}
	return ""
}

//line components/textarea.go:54

// Textarea renders the textarea component.
func Textarea(props TextareaProps) template.HTML {
	d := props
	_ = d
	w := &strings.Builder{}
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div class=\"field\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<label class=\"label\" for=\"")
	}
	if err == nil {
//line components/textarea.kyse.go:44
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
//line components/textarea.go:74
	}
	if err == nil {
		_, err = io.WriteString(w, "\">")
	}
	if err == nil {
//line components/textarea.kyse.go:44
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Label)))
//line components/textarea.go:82
	}
	if err == nil {
		_, err = io.WriteString(w, "</label>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<textarea\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tclass=\"textarea\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tid=\"")
	}
	if err == nil {
//line components/textarea.kyse.go:47
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
//line components/textarea.go:99
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\tname=\"")
	}
	if err == nil {
//line components/textarea.kyse.go:48
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
//line components/textarea.go:110
	}
	if err == nil {
		_, err = io.WriteString(w, "\"\n")
	}
//line components/textarea.kyse.go:49
	if d.Rows > 0 {
//line components/textarea.go:117
		if err == nil {
			_, err = io.WriteString(w, "\t\t\trows=\"")
		}
		if err == nil {
//line components/textarea.kyse.go:50
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Rows)))
//line components/textarea.go:124
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/textarea.kyse.go:52
	if d.Placeholder != "" {
//line components/textarea.go:132
		if err == nil {
			_, err = io.WriteString(w, "\t\t\tplaceholder=\"")
		}
		if err == nil {
//line components/textarea.kyse.go:53
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Placeholder)))
//line components/textarea.go:139
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/textarea.kyse.go:55
	if d.DescribedBy() != "" {
//line components/textarea.go:147
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-describedby=\"")
		}
		if err == nil {
//line components/textarea.kyse.go:56
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.DescribedBy())))
//line components/textarea.go:154
		}
		if err == nil {
			_, err = io.WriteString(w, "\"\n")
		}
	}
//line components/textarea.kyse.go:58
	if d.Error != "" {
//line components/textarea.go:162
		if err == nil {
			_, err = io.WriteString(w, "\t\t\taria-invalid=\"true\"\n")
		}
	}
//line components/textarea.kyse.go:61
	if d.Required {
//line components/textarea.go:169
		if err == nil {
			_, err = io.WriteString(w, "\t\t\trequired\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t>")
	}
	if err == nil {
//line components/textarea.kyse.go:64
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Value)))
//line components/textarea.go:180
	}
	if err == nil {
		_, err = io.WriteString(w, "</textarea>\n")
	}
//line components/textarea.kyse.go:65
	if d.Error != "" {
//line components/textarea.go:187
		if err == nil {
			_, err = io.WriteString(w, "\t\t<p id=\"")
		}
		if err == nil {
//line components/textarea.kyse.go:66
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
//line components/textarea.go:194
		}
		if err == nil {
			_, err = io.WriteString(w, "-error\" class=\"text-destructive text-sm\">")
		}
		if err == nil {
//line components/textarea.kyse.go:66
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Error)))
//line components/textarea.go:202
		}
		if err == nil {
			_, err = io.WriteString(w, "</p>\n")
		}
	}
//line components/textarea.kyse.go:68
	if d.Error == "" {
//line components/textarea.go:210
//line components/textarea.kyse.go:69
		if d.Hint != "" {
//line components/textarea.go:213
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t<p id=\"")
			}
			if err == nil {
//line components/textarea.kyse.go:70
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
//line components/textarea.go:220
			}
			if err == nil {
				_, err = io.WriteString(w, "-hint\" class=\"text-muted-foreground text-sm\">")
			}
			if err == nil {
//line components/textarea.kyse.go:70
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Hint)))
//line components/textarea.go:228
			}
			if err == nil {
				_, err = io.WriteString(w, "</p>\n")
			}
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	_ = err
	return template.HTML(w.String())
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = strings.Builder{}
)
